import { delimiter, join } from "node:path";
import { effectivePath, isExecutableFile, loginShell } from "./user-env";
import { decideProviderReadiness, type ProviderReadinessState, type ReadinessProbe } from "./provider-readiness-decision";
import { readinessCache, runReadinessProbe } from "./provider-readiness-probe";
import { MIN_CONTENT_BYTES, type SessionStore } from "./session-store-spec";
import { CARD_MESSAGE_CONTENT_NOTICE } from "./pasted-content-decision";
import type { ConfigHomeDecl } from "./config-home-decision";
import type { HealthCapability } from "./card-health";

/**
 * Os SEIS providers nativos, como constantes nomeadas — o autocomplete
 * importa no punhado de lugares que de fato comparam um id literal
 * (`resolveSpawn` via `$SHELL`/`ComSpec`, `checkAgentAvailability`
 * excluindo `bash`, docs vivas). Fora daqui, nada deve cravar um id:
 * a fonte por provider é a própria declaração (`ProviderDef.capacity`).
 */
export const NATIVE_PROVIDER_IDS = {
  bash: "bash",
  claude: "claude",
  codex: "codex",
  cursor: "cursor",
  antigravity: "antigravity",
  opencode: "opencode",
} as const;

export type NativeProviderId = (typeof NATIVE_PROVIDER_IDS)[keyof typeof NATIVE_PROVIDER_IDS];

/**
 * Um id de provider é uma STRING, não uma union fechada (2026-09-19).
 *
 * O que mudou e por quê: a union fechada era a segunda metade do mesmo
 * hardcode que a task de "provider dinâmico" veio remover — um CLI de
 * terceiro (cline, commandcode) não existe no código-fonte em lugar
 * nenhum, e escolher esse CLI é DADO (`providers-dynamic.ts`, arquivo de
 * config em `userData`), não uma edição de tipo. Com a union, um provider
 * que o usuário cadastrou não teria como ser NOMEADO sem mexer no repo.
 *
 * O que NÃO mudou: os seis nativos continuam existindo, com o mesmo
 * `buildArgs` escrito à mão de sempre — nenhum deles passa pelo
 * sintetizador de args dos dinâmicos. `NATIVE_PROVIDER_IDS` acima preserva
 * o autocomplete onde ele ainda importa; um id desconhecido continua
 * falhando onde sempre falhou (`resolveSpawn` → `null` → `binary_not_found`
 * no pty-registry), nunca em silêncio.
 */
export type ProviderId = string;

export type SpawnOpts = {
  resumeId?: string;
  /**
   * Fresh UUID generated by Stellar to IMPOSE on a brand-new session.
   * Distinct from `resumeId` (restore an existing session whose file
   * already exists). Measured 2026-09-13 (task c1064d95) against the
   * real CLIs: `claude` accepts `--session-id <uuid>` and creates the
   * session with that id; `cursor` accepts `--resume <uuid>` even when
   * the id does not exist yet and creates the session with it.
   *
   * RE-MEDIDO 2026-09-22 (task 201bd13b), em `cursor-agent` 2026.09.18: a
   * frase acima descreve a CLI de 2026-09-13. Hoje `--resume` é "Select a
   * session to resume" e a imposição tem flag PRÓPRIA (`--new-session-id`,
   * UUIDv4, exclusiva com `--resume`) — é ela que `buildArgs` manda. Uma
   * medição de CLI não expira sozinha: quem a cita declara a VERSÃO.
   * Never set together with a restore `resumeId`. `codex` /
   * `antigravity` / `opencode` reject or ignore an unknown id — do not
   * set this for them (see `canImposeSessionId`).
   */
  imposedSessionId?: string;
  continueLast?: boolean;
  model?: string;
  systemPrompt?: string;
  /** DESIGN-BACKLOG.md item 21, ponto 9, achado 1 — how many agent-
   * initiated (not human-initiated) spawns led to this one. `undefined`/
   * `0` for every human-triggered spawn (rail, radial menu) — a fresh
   * chain always starts here. Threaded into the process env
   * (AGENT_CANVAS_SPAWN_DEPTH, see pty-registry.ts) so a NEW spawn
   * request from THIS agent reports the right depth, and enforced as a
   * hard cap in message-bus.ts (MAX_SPAWN_DEPTH) before any consent
   * modal even shows. */
  spawnDepth?: number;
  /** Sticky item "spawn_agent effort" (2026-09-03) — Antigravity's CLI
   * requires `--effort` alongside certain models (`--model
   * gemini-3.1-pro` on its own falls back silently to a different model
   * with a warning, never actually running the one asked for). The range is
   * MODEL-DEPENDENT and was re-measured at RUNTIME 2026-10-01 (agy v1.2.14,
   * task 1c4f3b50): the `--help` advertises `low|medium|high|max`, but the
   * default model honors only `low|high` and `max` is honored by NO model.
   * The declared range (the one the spawn gate reads) lives on the
   * provider's `capacity.effort` below — this paragraph is only the
   * history. `model` stays
   * a plain string on purpose (every other provider only ever takes one)
   * — this is additive and provider-specific, `undefined` for every
   * provider whose `buildArgs` doesn't read it.
   *
   * 2026-09-09 (DESIGN-BACKLOG.md §2.1, real cost to the repo's owner) —
   * `claude`'s `buildArgs` below now reads this too: confirmed live via
   * `claude --help` (v2.1.269, re-checked 2026-09-12) that it has its own
   * `--effort <level>` flag, `low|medium|high|xhigh|max` — a wider range
   * than antigravity's. Widened from `"low" | "high"` to plain `string`
   * (review adversarial, same day, achado 2) so a card resumed with a
   * value outside the app's own write-path enum (e.g. claude's `xhigh`)
   * round-trips through here unmolested instead of the type forcing a
   * lossy coercion somewhere upstream — see card-types.ts's
   * `TerminalCardData.effort` doc comment for the full reasoning.
   *
   * 2026-09-15: a spawn_agent that passes `effort` for a provider whose
   * `capacity.effort` mechanism is "none" is now REFUSED at the gate
   * (spawn-profile-decision.ts), not accepted-and-dropped — the
   * pre-fix behavior for bash/codex/cursor/opencode was exactly the
   * silent-substitution class described above. */
  effort?: string;
  /** Internal only — never set by the renderer/IPC caller. Injected by
   * `pty-registry.ts::spawn()` from its own closed-over `mcpUrl` so
   * `buildArgs` below can register the MCP server per-provider without
   * every call site needing to know the port. */
  mcpUrl?: string;
  brief?: string;
  /**
   * Task this card was spawned to serve (`spawn_agent({ taskId })` or
   * auto-dispatch). Optional in earnest: spawn without a task stays
   * first-class and this stays unset. Threaded into
   * `AGENT_CANVAS_TASK_ID` (pty-registry.ts) only when present — never a
   * placeholder. Not read by `buildArgs`.
   */
  taskId?: string;
};

// ---------------------------------------------------------------------------
// Capacity contract (DESIGN-BACKLOG.md §0, 2026-09-12)
//
// One declaration per provider — system-prompt injection? MCP registration
// (which mechanism)? acbridge on PATH? — with report-discovery DELIVERY
// derived from that declaration (`deriveReportDiscovery`), not chosen
// case-by-case at call sites. A provider that cannot teach an agent to
// report by any path must fail visibly at spawn (see
// bash-discovery-decision.ts), never silently at report time.
//
// Measurement that shaped this (2026-09-12): Cursor's headless CLI (`agent`)
// DOES read `~/.cursor/mcp.json` — confirmed by pointing HOME at a temp
// dir with a probe server and seeing `agent mcp list` pick it up. The
// global registration, shim binary, and HTTP endpoint can all be healthy
// and `agent mcp list` still say `stellar: ready`, yet live cursor cards
// reported "sem tools Stellar" and never called report. MCP alone is
// therefore declared as a capacity but is NOT treated as a sufficient
// report-discovery path; without a system-prompt flag the derived delivery
// is scrollback (acbridge tip), matching the owner's "flag → scrollback →
// fail spawn" rule.
// ---------------------------------------------------------------------------

/** How (if at all) this provider accepts an injected system/developer prompt.
 *
 * `flag` (2026-09-19) is the plain "there is a real flag that takes the
 * block" case — declared by a DYNAMIC provider whose CLI was measured to
 * have one (cline: `-s`), and synthesized into argv by
 * `providers-dynamic.ts`. It is deliberately NOT the shape the two native
 * mechanisms below use: `append-system-prompt` (claude) and
 * `developer_instructions` (codex) each name a wiring that already exists
 * by hand in that provider's `buildArgs`, and renaming them into `flag`
 * would only hide which CLI reads what. The distinction that matters to
 * every consumer is just `mechanism !== "none"` (see
 * `deriveReportDiscovery`), and every non-`none` mechanism keeps that. */
export type SystemPromptCapability =
  | { mechanism: "append-system-prompt" }
  | { mechanism: "developer_instructions" }
  | { mechanism: "flag"; flag: string }
  | { mechanism: "none" };

/**
 * The shape of ONE server entry inside the persistent config file — what a
 * registrar writes under `configKey`. Declared, not chosen at write time,
 * because the CLIs disagree about the entry and the next task (MCP
 * registration for dynamic providers) has to know which one to emit.
 */
export type McpServerShape =
  /** `{ command: <path> }` (args/env optional) — claude/cursor/cline/
   * commandcode-style `mcpServers` entry pointing at the stdio shim. */
  | "stdio-command"
  /** opencode's `{ type: "local", command: [<path>], enabled: true }`. */
  | "local-array"
  /**
   * Servidor REMOTO direto no endpoint HTTP do main — `{ url: <...> }` (cursor)
   * ou `{ type: "http", url: <...> }` (commandcode/agy/opencode). ZERO processo
   * por card: some o shim stdio. O `url` é o template que os CLIs interpolam do
   * ambiente do card (`${env:AGENT_CANVAS_MCP_URL}?card=${env:AGENT_CANVAS_CARD_ID}`),
   * porque a porta é efêmera e a identidade é por card. Ver `mcp-registration.ts`.
   */
  | "http-url"
  /** Task 7d3be060 — a forma REMOTA do `opencode`: `{ type: "remote", url }`
   * (não `"http"`). Era escrita por uma função à mão; agora é declarada no
   * catálogo genérico e o caminho DECLARADO a emite. O `url` usa a mesma
   * interpolação por env, na sintaxe de `urlSyntax`. */
  | "remote-url";

/**
 * A SINTAXE com que uma CLI interpola variáveis de ambiente num `url` de
 * config — MEDIDA por CLI, nunca suposta (task f7a2ac84 R4):
 *
 *   - `"dollar-env"` → `${env:VAR}`  (cursor, MEDIDO: 53 tools)
 *   - `"brace-env"`  → `{env:VAR}`   (opencode, MEDIDO: conecta; o `${env:}`
 *     dele dá "Invalid MCP URL" — é sintaxe PRÓPRIA, não a do cursor)
 *
 * Declarar aqui (e o registrador emitir o que foi declarado) é o que impede o
 * próximo provider de herdar a sintaxe errada por copiar-e-colar.
 */
export type McpUrlSyntax = "dollar-env" | "brace-env";

/** How the stellar MCP server is registered for this provider. */
export type McpRegistrationCapability =
  | { mechanism: "ephemeral-flag" }
  | {
      mechanism: "global-config";
      /**
       * Onde o arquivo de config persistente DAQUELE CLI mora, com `~` —
       * resolvido contra `registrationHome()` em `mcp-registration.ts`
       * (que é o que a suíte de verificação sobrepõe para não escrever no
       * `$HOME` real). Opcional porque os TRÊS nativos `global-config`
       * declarados hoje já têm o caminho escrito no registrador que de
       * fato o usa — declarar de novo aqui seria uma segunda fonte do
       * mesmo fato, e o registrador ainda não lê esta declaração. Quem
       * não tem registrador (todo dinâmico) declara, e é a única fonte.
       */
      configPath?: string;
      /** A chave do arquivo que contém o mapa de servidores (`mcpServers`). */
      configKey?: string;
      /** A forma da entrada — ver `McpServerShape`. */
      serverShape?: McpServerShape;
      /** A sintaxe de interpolação do `url` DESTA CLI — ver `McpUrlSyntax`.
       * Só tem efeito nas formas que emitem `url` (`http-url`). */
      urlSyntax?: McpUrlSyntax;
    }
  | { mechanism: "none" };

/**
 * Como o id de sessão chega ao argv — declarado, nunca inferido.
 *
 * Antes (até 2026-09-19) isto era a lista fechada
 * `IMPOSE_SESSION_ID_PROVIDERS` em providers.ts: um provider novo não
 * tinha como se declarar imponível sem editar o array, e um dinâmico
 * (registrado em runtime) não apareceria nele de jeito nenhum. Agora a
 * pergunta é feita ao próprio provider, e `imposeSessionIdProviders()`
 * deriva a lista de quem respondeu sim.
 *
 * As flags estão aqui — e não só os booleanos — porque são elas que o
 * sintetizador de args de um provider dinâmico emite; um nativo continua
 * com seu `buildArgs` à mão, então aqui elas são o registro medido do que
 * aquele buildArgs já faz (claude: `--resume` restaura, `--session-id`
 * CRIA; cursor: `--resume` faz os dois).
 */
export type SessionCapability = {
  /** `true` só onde a CLI aceita um id escolhido pelo Stellar num spawn
   * novo (medido em 2026-09-13, task c1064d95). Um provider que não impõe
   * nunca recebe `imposedSessionId` (`shouldImposeSessionId`). */
  canImposeSessionId: boolean;
  /** Flag + valor que RETOMA sessão existente. Ausente onde não existe
   * (codex: `resume` é subcomando, ver o próprio provider) ou onde não foi
   * medido — nunca inventamos uma. */
  resumeFlag?: string;
  /** Flag + valor que CRIA a sessão com o UUID gerado. Igual a
   * `resumeFlag` onde a CLI usa uma só (cursor, cline); diferente onde
   * são duas (claude). Exigida quando `canImposeSessionId` é `true`. */
  imposeFlag?: string;
  /** Flag booleana "continue a sessão mais recente". Ausente = o provider
   * não tem uma (ou não foi medida) e `continueLast` não vira argv. */
  continueFlag?: string;
  /** A CLI retoma uma sessão por um id OBSERVADO sem que ele caiba numa
   * flag — o `codex` usa o SUBCOMANDO `resume <id>` (ver o provider), que
   * uma declaração flag-shaped não expressa e cujo `buildArgs` à mão é a
   * implementação. `true` só onde foi medido. Ausente = a resposta sai só
   * das flags (`resumeFlag`/`imposeFlag`/`continueFlag`). É isto que faz
   * `providerResumesById` responder a pergunta "dá para retomar esta CLI?"
   * sem uma segunda lista. */
  resumeById?: boolean;
  /** ONDE ESTA CLI GUARDA SESSÃO (task 2ea0269f) — a declaração que dá ao
   * rodapé do card de onde vir. A LINGUAGEM é `SessionStore`
   * (`session-store-spec.ts`) e o único leitor é `session-watch.ts`; aqui é
   * só o valor MEDIDO de cada CLI.
   *
   * AUSENTE = este provider não é observável, e isso é honesto: sem âncora
   * medida de cwd e de tempo, varrer o disco às cegas acharia o arquivo de
   * outro card. Um store pode declarar só a descoberta (sem `read`) — a
   * resposta de leitura continua saindo da declaração, nunca inventada. */
  store?: SessionStore;
};

// DESIGN-BACKLOG.md §2.1 "effort do card não é persistido" — per-provider
// ranges re-measured 2026-09-12 against the live CLIs (not the comments):
//
// - `claude --help` (v2.1.269): `--effort <level>` is
//   `low, medium, high, xhigh, max`. An unknown value is NOT rejected —
//   the CLI prints `Warning: Unknown --effort value '…' — ignoring it and
//   using the default effort` and continues. That is the same silent-
//   substitution class this gate exists for, so claude NOW has a list
//   here (the 2026-09-10 comment that it "accepts anything callers send
//   it, so there's nothing to refuse" was empirically false).
// - `agy` — re-MEASURED at RUNTIME 2026-10-01, v1.2.14 (task 1c4f3b50).
//   The `--help` is NOT proof: the GLOBAL flag validator ANNOUNCES
//   `low|medium|high|max` (an invalid value lists all four), yet the real
//   range is PER MODEL:
//     * default (`gemini-3.1-pro`, no `--model`): only `low`/`high` — the
//       `--effort medium` and `--effort max` runs exit 1 with
//       "gemini-3.1-pro has no medium/max effort (available: low, high)";
//     * `medium`: honored by a model whose NAME carries the level
//       (`gemini-3.8-flash-medium --effort medium` → exit 0);
//     * `max`: honored by NO model (no `-max` variant in `agy models`; every
//       `--effort max` errors).
//   DECISION: `max` is NOT declared — help announcing it is not honoring it,
//   and nothing honors it. `low|medium|high` stay declared as the levels the
//   CLI accepts, but `medium` carries the model caveat above (a bare spawn,
//   no `--model`, cannot honor it): a model-conditional range is not
//   expressible in this declaration, so the caveat lives here rather than
//   being silently dropped. (The 2026-09-12 v1.2.2 note listened to the
//   GLOBAL validator because it passed `--model <fake>` — that is not a real
//   spawn's range.) Evidence: tests/unit/fixtures/antigravity-effort/
//   (8 real runs with exit codes).
//
// DECISION (documented here, not just in the session report): a
// `spawn_agent` whose provider has a known range, with an effort outside
// that range, is REFUSED (`ok: false`, no card created), never silently
// remapped to the nearest supported value. Mapping in silence repeats the
// exact bug class this whole fix exists for — the user asked for X, got
// Y, and the app never said so ("a sessão era um opus medium... voltei
// como high e custou muito" was ITSELF a silent substitution, just one
// the app didn't even choose on purpose). A refusal surfaces immediately,
// in the same `ok:false` channel every other spawn precondition in
// message-bus.ts's `spawn_agent` handler already uses (missing provider,
// spawn depth limit) — the caller sees exactly why, before any process
// or card is created, and can retry with a value that actually works.
// The alternative (spawn anyway with the raw value) is worse than
// either: it would just move the same silent-substitution failure one
// layer down, into the CLI's own warning/error, where nothing in this
// app surfaces it as an error at all.
//
// 2026-09-15: the ranges moved from two hardcoded `Set`s in
// message-bus.ts into these per-provider declarations, and the same
// refuse-never-silently-remap rule GAINED a second half — a provider that
// cannot honor `effort` at all now refuses it too (the old behavior was
// accept-and-drop: any value passed zod, never became argv, and nobody
// was told). The pure decision that reads this declaration lives in
// spawn-profile-decision.ts.
/** Whether this provider can honor a caller-chosen reasoning effort on
 * its spawn argv, and with which MEASURED range. Single source: the
 * spawn gate (message-bus.ts via spawn-profile-decision.ts) reads this
 * declaration — no per-provider `if` grows anywhere else. */
export type EffortCapability =
  | { mechanism: "flag"; flag: string; values: readonly string[] }
  | {
      mechanism: "none";
      /** Why — the refusal sentence is DERIVED from this, so it stays
       * honest: `no-flag` (measured absence) may say the CLI has no
       * flag; `unmeasured` may only say nothing was ever measured or
       * sent; `shell` is not an agent CLI at all. */
      reason: "shell" | "no-flag" | "unmeasured";
    };

/** Whether this provider can honor a caller-chosen model on its spawn
 * argv. Every agent CLI takes a model flag (measured per provider, see
 * each buildArgs); a shell does not. The opencode qualified-spec trap
 * (a model that doesn't resolve in its catalog falls back to a default
 * IN SILENCE) is NOT a capacity question — the flag exists and is
 * honored, the VALUE may still not resolve — and is documented in the
 * opencode provider's own comment below. */
export type ModelCapability =
  | { mechanism: "flag"; flag: string }
  | { mechanism: "none"; reason: "shell" };

export type ProviderRole = "agent" | "shell";

/**
 * Como ESTE provider sinaliza que um TURNO ACABOU (task 0dd5c145) — declarado
 * por provider, nunca perguntado por id.
 *
 * A regra que isto substitui: até aqui o renderer decidia por
 * `id === "claude"` (`terminal-turn-signal.ts`), e a afirmação embutida nisso
 * — "só o claude tem fim de turno" — já era FALSA. O commandcode tem um
 * sistema de hooks compatível com o do Claude Code (`Stop`, medido no bundle
 * instalado: `~/.commandcode/settings.json`), e a TUI dele fecha o turno com
 * um marcador de tela próprio. Medir a AUSÊNCIA de algo no NOSSO repo não
 * prova a ausência da capacidade do outro lado.
 *
 * AUSENTE = este provider não sinaliza fim de turno, e isso é honesto: a UI
 * não promete o que não existe — a barra de atividade cai no silêncio e
 * nenhum aviso de SO é disparado por aproximação. Mesma regra da ausência de
 * `capacity.effort`.
 *
 * Os dois mecanismos NÃO são equivalentes para quem consome:
 *   - `hook` — o CLI entrega o EVENTO (o `Stop` que o `buildArgs` daquele
 *     provider instala, chamando `acbridge turn-complete`); o sinal chega
 *     nomeado (`pty:turn-complete`) e é FATO, não leitura de tela;
 *   - `screen` — marcador de TEXTO no scrollback: mais barato e mais FRÁGIL
 *     (uma atualização da CLI muda a frase e o sinal some sem avisar
 *     ninguém). O gate de notificação de SO distingue os dois exatamente por
 *     isso — ver `TerminalCard.tsx`.
 */
export type TurnEndSignal =
  | { mechanism: "hook" }
  | { mechanism: "screen"; pattern: RegExp };

/**
 * The screen state of a turn, declared per provider. `turnEnd` above fires ONCE
 * when its marker scrolls past; a TUI that keeps repainting afterwards (so the
 * byte clock never ages) needs the STATE: the turn is over when an end marker is
 * on screen and the working marker (spinner / "esc to interrupt") does not come
 * after it. Both patterns run over the ANSI-stripped tail; the LAST occurrence
 * of each decides (see `screen-turn-state.ts`).
 *
 *   - `working`: what the screen shows only while the agent is busy;
 *   - `ended`: what the screen shows once the turn is over (a "Worked for 27m"
 *     line, or an idle footer that replaces the busy one).
 *
 * Measured on real cards, never copied from another provider — the samples are
 * pinned in tests/unit/fixtures/screen-turn/.
 */
export type ScreenTurnDecl = { working: RegExp; ended: RegExp };

/**
 * MEASURED SCREEN TURN the shipped JSON does not declare — same reason and same
 * place as `MEASURED_MID_TURN_QUEUES`/`MEASURED_HEALTH`: `commandcode` is
 * DYNAMIC, its screen was measured after the JSON existed, and the table is
 * applied at registration so the spec round-trip stays intact.
 *
 * Measured (card 98576220 and the fixtures): while working the spinner line is
 * `○ Crystallizing…  esc to interrupt • 6m 18s • ↓ 141.7k`; when the turn ends
 * the line `✻ Worked for 9m 51s` is printed and the spinner is gone. Note
 * `? for shortcuts` is on screen in BOTH states, so it is no marker.
 */
const MEASURED_SCREEN_TURNS: Readonly<Record<ProviderId, ScreenTurnDecl>> = {
  commandcode: {
    working: /esc to interrupt/,
    ended: /Worked for (?:\d+h\s*)?(?:\d+m\s*)?\d+(?:s| seconds?)/,
  },
};

/**
 * A AÇÃO ONE-SHOT (o "Resumir" do Rail) — declarada, não adivinhada por `id`
 * (task efc5b6fd).
 *
 * EVIDÊNCIA (task 34887bbc). O R4 de efc5b6fd mostrou que a declaração de
 * cursor/agy dizia "mesmas flags do claude" — COPIADA, não medida — e o próprio
 * comentário de `effort` logo abaixo admitia que o cursor nunca tinha sido
 * medido. Medido de novo em 2026-10-01, em DUAS camadas que o texto antigo
 * juntava numa só:
 *   - FLAGS, do `--help` real desta máquina: `cursor-agent` v2026.09.18-9a7762b
 *     e `agy` v1.2.14 anunciam `-p/--print` (não-interativo) e
 *     `--output-format` com `json` entre os valores;
 *   - FORMA do JSON (o `--help` NÃO a prova), de uma EXECUÇÃO real:
 *     `cursor-agent --mode ask -p "…" --output-format json` devolveu
 *     `{"type":"result",…,"result":"pong",…}`, e `agy -p "…" --output-format
 *     json` devolveu `{"…","response":"pong\n",…}`. `.result` (cursor, e claude)
 *     e `.response` (agy) são exatamente os campos que `extractJsonResult`
 *     (ai-action.ts) lê. As saídas reais — `--help` e JSON — estão em
 *     `tests/unit/fixtures/one-shot/` e são presas pelo teste homônimo.
 *
 *   - claude, cursor-agent, agy: `-p <prompt> --output-format json` → UM
 *     objeto JSON (ver as duas camadas acima), texto em `.result`/`.response`;
 *   - codex: `exec <prompt> -o <arquivo>` → o texto final cai no arquivo;
 *   - commandcode: `-p, --print [query]` com o default `--output-format text`
 *     imprime a resposta e sai. O json dele é "NDJSON event stream", NÃO um
 *     objeto final — por isso a declaração dele é texto, não json;
 *   - cline: o prompt é POSICIONAL e `-p` significa `--plan` (não existe
 *     `--print`); o modo default é act com auto-approve. Não há one-shot
 *     medido que devolva o texto final;
 *   - opencode: `run <message> --format json` é stream NDJSON.
 *
 * AUSÊNCIA DESTE CAMPO = ESTE PROVIDER NÃO FAZ ONE-SHOT, e a UI não oferece a
 * ação (regra dura da task: nunca oferecer e falhar). É o mesmo critério do
 * `effort` com `mechanism: "none"` e do `turnEnd` ausente.
 *
 * O nome segue o precedente do repo (`delivery.briefMechanism`,
 * `session.resumeFlag`): mecanismo + o dado que ele precisa. `args` é o argv
 * com dois placeholders — `{prompt}` e `{outFile}` — e `result` diz COMO ler a
 * saída, que é a diferença que o `id` não conseguia expressar.
 */
export type OneShotCapability =
  | { mechanism: "none" }
  | {
      mechanism: "argv";
      args: string[];
      result: "stdout-json" | "stdout-text" | "out-file";
    };

export type ProviderCapacity = {
  role: ProviderRole;
  systemPrompt: SystemPromptCapability;
  mcp: McpRegistrationCapability;
  /**
   * Every card gets `binDir` prepended to PATH in `pty-registry.ts`, so
   * this is `true` for every current provider. Declared (not assumed) so
   * derivation reads one field instead of a second handwritten list.
   */
  acbridgeOnPath: boolean;

  /** Since 2026-09-15: reasoning-effort support is DECLARED here too — a
   * spawn_agent passing `effort` for a provider whose mechanism is
   * "none" is refused by the gate (spawn-profile-decision.ts), never
   * accepted and silently dropped (the pre-fix behavior, measured
   * 2026-09-15: any effort passed zod for bash/codex/cursor/opencode,
   * never became argv, and nobody was told). */
  effort: EffortCapability;
  /** Model support — refused for `bash` (a shell has no model). Accepted
   * for every agent CLI; the opencode catalog caveat lives on the
   * provider's own comment. */
  model: ModelCapability;

  /**
   * A ação one-shot ("Resumir") — ver `OneShotCapability`. AUSENTE = este
   * provider não a faz, e a UI não a oferece. Declarado só onde foi medido.
   */
  oneShot?: OneShotCapability;

  /**
   * CARD HEALTH — how to read, from the screen copy the app already keeps, the
   * context tokens in use and the provider's plan/quota line. See
   * `card-health.ts` for the whole rationale. ABSENT = this provider exposes
   * nothing, and the honest answer is `{ context: null, quota: null }` — never
   * an invented number.
   *
   * DECLARED, never an `if (provider === …)`: the patterns and the window are
   * measured per CLI, in the same place as `effort`/`model`/`session`.
   */
  health?: HealthCapability;

  /** Como o id de sessão entra no argv — ver `SessionCapability`. O que
   * `shouldImposeSessionId`/`canImposeSessionId` leem (2026-09-19): a
   * resposta é do provider, nativo ou dinâmico, não de uma lista. */
  session: SessionCapability;

  /** Como a CLI gerencia instruções (brief e TUI follow-ups) */
  delivery: {
    /** 
     * Como o brief é passado no spawn.
     * 'positional' (claude, codex, cursor) — emitido como `-- <brief>` na
     *   cauda do argv (`spawnArgv`); exige que o parser da CLI honre
     *   `--`, medido para os três (ver `END_OF_OPTIONS`).
     * 'flag' (opencode: --prompt, antigravity: -i)
     * 'none' (bash)
     */
    briefMechanism: "positional" | "flag" | "none";
    briefFlag?: string;
    
    /** 
     * Vocabulário de tela DAQUELE provider indicando o início de um turno após receber input na TUI.
     * Fica undefined se não foi medido (evitando inventar regras) ou não for TUI de agente.
     */
    submitStartedPattern?: RegExp;

    /**
     * Como este provider sinaliza o FIM de um turno — ver `TurnEndSignal`.
     * Ausente = não sinaliza (ou não foi medido), e a UI não promete.
     */
    turnEnd?: TurnEndSignal;

    /**
     * How to read, from the screen tail the app already keeps, whether the turn
     * is OVER right now — ver `ScreenTurnDecl`. Declared per provider as data,
     * next to the trust-prompt and quota patterns; ABSENT = not measured on a
     * real card, and the honest answer is "unknown".
     */
    screenTurn?: ScreenTurnDecl;

    /**
     * Mid-turn holding UI: submit while the agent is busy parks the text
     * instead of injecting it. Measured 2026-09-14 on cursor-agent only
     * (`follow-ups` box + `enter steer` footer). Absent = this provider
     * has no such queue (or it was not measured) — callers must not
     * invent an `if (provider === "cursor")` elsewhere; derive from here.
     */
    midTurnQueue?: {
      /** Screen chrome of the park box (new since the delivery write). */
      parkedPattern: RegExp;
      /**
       * Key that injects the selected parked item into the live turn.
       * Measured cursor/cline: bare Enter. At most ONE press after park —
       * never the unsent-retry loop (owner 2026-09-11: 5× paste → exit 143).
       *
       * AUSENTE = a fila do provider SE ENTREGA SOZINHA quando o turno
       * termina (medido no commandcode, 2026-10-04: `Queued (N)` + `›`).
       * Nesse caso NENHUMA tecla é pressionada depois do park — a regra do
       * dono é nunca um Enter cego. Ver `midTurnQueueAutoDelivers`.
       */
      steerKey?: string;
    };
  };
};

/**
 * FILAS MID-TURN MEDIDAS que o catálogo embarcado não declara (2026-10-04,
 * board 64). Os providers NATIVOS trazem a fila no próprio def (cursor) ou no
 * dado (cline); um provider DINÂMICO cuja capacidade foi medida DEPOIS só
 * ganharia a fila editando o JSON — e o JSON é a declaração do provider, não o
 * lugar de um fato que o app mediu em runtime. Esta tabela é aplicada no
 * REGISTRO (`registerDynamicProviders`), nunca no spec: o def vivo e o
 * `providerCapacity` concordam, e o round-trip spec→def segue intacto.
 *
 * MEDIDO no commandcode: `send_to_card` para um card ocupado mostra
 *   `Queued (N)` seguido de `› <início do texto>`
 * e a fila SE ENTREGA SOZINHA quando o turno termina — por isso NÃO há
 * `steerKey` (a ausência é o fato; nenhuma tecla é pressionada depois do park).
 */
const MEASURED_MID_TURN_QUEUES: Readonly<Record<ProviderId, NonNullable<ProviderCapacity["delivery"]["midTurnQueue"]>>> = {
  commandcode: {
    parkedPattern: /\bqueued\s*\(\d+\)[\s\S]*?›/i,
  },
};

/**
 * MEASURED CARD HEALTH the shipped catalog does not declare. Same reason and
 * same place as `MEASURED_MID_TURN_QUEUES` above: `commandcode` is DYNAMIC
 * (from `data/providers.builtin.json`), and its health reading was measured
 * after that JSON existed — the table is applied at REGISTRATION
 * (`registerDynamicProviders`), never to the spec, so the live def and
 * `providerCapacity` agree and the spec→def round-trip stays intact.
 *
 * Only QUOTA is declared, and the reason CONTEXT is not is a measurement worth
 * stating: the spinner token count (`… • ↓ 8.0k`, `… • ↓ 12.4k` on live cards)
 * is the TURN's volume — it resets and grows every turn, so it is NOT the
 * session context and must never be shown as one. commandcode's real context
 * indicator (`Context left before auto-compact N%`, `~X until auto-compact`)
 * exists in the CLI but draws only at high usage and was absent from every
 * screen read, so there is no recorded sample to pin a pattern to; and the
 * session store's per-message `usage` tokens carry no window, so no threshold
 * could be honest. Context stays undeclared — `null`, never a wrong number.
 */
const MEASURED_HEALTH: Readonly<Record<ProviderId, HealthCapability>> = {
  commandcode: {
    quota: {
      // The whole footer LINE becomes `quota.text` (it carries "13.3 credits left").
      pattern: /Plan:\s*([\d.]+)%\s*used/i,
      source: "commandcode plan footer",
    },
  },
};

/**
 * A fila do provider SE ENTREGA SOZINHA? Sim quando ele declara uma fila SEM
 * `steerKey`: o provider a injeta no turno por conta própria quando ele termina,
 * então não há tecla a pressionar (`commandcode`). Com `steerKey` (cursor,
 * cline), quem decide injetar é o remetente via `steer:true`.
 */
export function midTurnQueueAutoDelivers(queue: ProviderCapacity["delivery"]["midTurnQueue"]): boolean {
  return !!queue && !queue.steerKey;
}

/**
 * How an agent learns it must call `report` / `acbridge report`.
 * Derived from `ProviderCapacity` — never stored as a parallel fact.
 */
export type ReportDiscovery =
  | "system_prompt"
  | "scrollback"
  | "not_applicable"
  | "unreachable";

/**
 * Derive report-discovery delivery from a capacity declaration.
 * Order: system-prompt flag → scrollback (if acbridge on PATH) →
 * unreachable (spawn must refuse). Shell cards are not agents.
 */
export function deriveReportDiscovery(capacity: ProviderCapacity): ReportDiscovery {
  if (capacity.role === "shell") return "not_applicable";
  if (capacity.systemPrompt.mechanism !== "none") return "system_prompt";
  if (capacity.acbridgeOnPath) return "scrollback";
  return "unreachable";
}

/**
 * The channel a report is EXPECTED to arrive on for this provider —
 * distinct from `ReportDiscovery`, which is how the agent LEARNS it must
 * report. `mcp` means the `report` tool should be in the agent's catalog
 * (registered either by an ephemeral flag in `buildArgs` or by the
 * persistent config `mcp-registration.ts` writes); `acbridge` means the
 * CLI on PATH is the only path; `unreachable` means neither.
 *
 * Derived, never declared: the same `capacity.mcp` that decides whether
 * `ensureMcpRegistered` acts decides this, so the two cannot disagree.
 * Both channels land in the same row (`promoteReportVerdict` in
 * mcp-server.ts unifies them), which is what lets the agent-facing rule
 * stay a single sentence: if `report` is in your catalog use it,
 * otherwise `acbridge report` with `verdict` inside the JSON. The agent
 * decides at runtime by looking at its own catalog — the derived value
 * here is the expectation, not a promise the transport always kept (see
 * the 2026-09-13 whitelist finding in mcp-registration.ts).
 */
export type ReportChannel = "mcp" | "acbridge" | "unreachable";

export function deriveReportChannel(capacity: ProviderCapacity): ReportChannel {
  if (capacity.mcp.mechanism !== "none") return "mcp";
  if (capacity.acbridgeOnPath) return "acbridge";
  return "unreachable";
}

/**
 * POSIX end-of-options marker. Everything after it is an operand, so a
 * positional brief placed behind it can never be swallowed by a
 * preceding VARIADIC option — the 2026-09-13 boot death (card 471):
 * `claude --mcp-config <json> <brief>` parsed the brief as a second
 * config path (`ENAMETOOLONG`), because `--mcp-config <configs...>` is
 * variadic and eats every following non-option token. It also stops a
 * brief that starts with `-` (a markdown bullet, say) from being read as
 * an unknown option and dropped in silence (measured: `claude --print
 * "-diga"` → "Input must be provided", exit 1; with `--` → answered).
 *
 * Honoured by every positional provider's real parser, measured
 * 2026-09-13: claude (commander, `-- "diga apenas OK"` → OK), cursor
 * `agent` (commander, same probe → OK), codex (clap, `-- --help` did not
 * print help — the token became the PROMPT). A future positional
 * provider whose parser does NOT honour `--` must be measured before
 * being declared positional here.
 *
 * Consequence that shapes `spawnArgv` below: the brief fragment MUST be
 * the argv tail. Any option pushed after `--` would itself become an
 * operand — which is why `buildArgs` no longer sees `brief` at all.
 */
export const END_OF_OPTIONS = "--";

/**
 * Argv fragment implied by `delivery` for a spawn brief. One place —
 * `buildArgs` must not invent a second form (positional vs flag vs
 * none). Empty when there is no brief or the provider cannot take one
 * on argv (`bash`). Positional briefs ride behind `END_OF_OPTIONS`.
 */
export function briefArgvFragment(
  delivery: ProviderCapacity["delivery"],
  brief: string | undefined,
): string[] {
  if (!brief) return [];
  if (delivery.briefMechanism === "positional") return [END_OF_OPTIONS, brief];
  if (delivery.briefMechanism === "flag" && delivery.briefFlag) {
    return [delivery.briefFlag, brief];
  }
  return [];
}

/** Whether `args` actually carry `brief` the way `delivery` declares. */
export function argsCarryDeclaredBrief(
  args: readonly string[],
  delivery: ProviderCapacity["delivery"],
  brief: string,
): boolean {
  const fragment = briefArgvFragment(delivery, brief);
  if (fragment.length === 0) return false;
  for (let i = 0; i <= args.length - fragment.length; i++) {
    if (fragment.every((part, j) => args[i + j] === part)) return true;
  }
  return false;
}

/**
 * Empirical: this provider's spawn argv carries `brief` as declared.
 * Spawn dispatch uses this for `canArgv` so a stale declaration cannot
 * drop the text — the typing fallback still fires.
 */
export function argvCarriesDeclaredBrief(providerId: string, brief: string): boolean {
  const provider = providerById(providerId);
  if (!provider) return false;
  return argsCarryDeclaredBrief(spawnArgv(provider, { brief }), provider.capacity.delivery, brief);
}

/**
 * The full argv for a spawn: the provider's hand-written flags, then the
 * brief in the form `delivery` declares — ALWAYS as the tail. This is the
 * one place that decides WHERE the brief goes; `buildArgs` cannot even
 * read `opts.brief` (see `ProviderDef.buildArgs`'s type), so no provider
 * can put it back in the middle of its flags, where a variadic option
 * would eat it (the `--mcp-config` death, see `END_OF_OPTIONS`).
 */
export function spawnArgv(provider: ProviderDef, opts: SpawnOpts): string[] {
  const { brief, ...flagOpts } = opts;
  return [...provider.buildArgs(flagOpts), ...briefArgvFragment(provider.capacity.delivery, brief)];
}

// DESIGN-BACKLOG.md item 21, ponto 9 — the primary agent-facing interface
// is now the MCP server (mcp-server.ts) for providers that speak MCP;
// acbridge stays as the CLI fallback (see its own header comment). Kept
// short — MCP tool descriptions are self-documenting, this is just a
// nudge to look for them, not a manual.
//
// AGENT-FACING — DO NOT TRANSLATE (DESIGN-BACKLOG.md §2.1 i18n).
// Reader is a model, not a human. English is correct. Listed in
// `src/shared/i18n/agent-facing.ts`. A phase-2 string sweep that pulls
// this into `t()` would change agent behaviour with no test catching it.
export const ACBRIDGE_HINT =
  "You're running inside agent-canvas, a board of cards. If an MCP server " +
  "named `stellar` is connected, prefer its tools (list/send/open/spawn/" +
  "close_card/snapshot/page-text/read_card/card_status/report/read_report — read " +
  "each tool's own description). Otherwise a CLI `acbridge` is on your " +
  "PATH with the same capabilities (`acbridge` with no args prints " +
  "usage). If another card spawned you to do a task, report a structured " +
  "result when you finish it, even if you keep running afterward: if a " +
  "tool named `report` is in your tool catalog, call it; otherwise run " +
  "`acbridge report '<json>'` with `verdict` inside the JSON. Same " +
  "payload, same record either way. Use these only when it genuinely " +
  "helps the task at hand.\n\n" +
  // task 889dd934 — a marca de conteúdo card→card (ver
  // pasted-content-decision.ts, que também produz o texto do PTY). Depende
  // DESTA frase: sem ela o guia do Opus 5.5 é explícito que o bloco colado não
  // é resistido. Injetada por `composeSystemPrompt` no mecanismo que cada
  // provider já declara (`systemPrompt`: claude `--append-system-prompt`,
  // cline `-s`, codex `developer_instructions`, …), nunca num canal novo.
  CARD_MESSAGE_CONTENT_NOTICE;

/** The custom prompt describes the task; ACBRIDGE_HINT describes the runtime
 * environment. Keep both, in that order, separated by a blank line so the
 * task remains the first thing the provider sees while the environment hint
 * stays legible as a distinct block. Trimming also makes empty or
 * whitespace-only prompts behave like an omitted prompt instead of creating
 * a separator with no task text around it. */
export function composeSystemPrompt(systemPrompt?: string): string {
  const taskPrompt = systemPrompt?.trim();
  return taskPrompt ? `${taskPrompt}\n\n${ACBRIDGE_HINT}` : ACBRIDGE_HINT;
}

/** Um comando por família de SO — `npm install -g` já é igual nas duas,
 * mas os installers via `curl | bash` (cursor/antigravity) não existem no
 * Windows (achado ao vivo, 2026-09-03: "no Windows não tem bash"), que
 * tem seu próprio instalador PowerShell nativo em cada um desses
 * provedores (confirmado contra a documentação real de cada um). */
type InstallCommand = { posix: string; windows: string };

/** What `buildArgs` gets: every spawn option EXCEPT the brief. */
export type ProviderFlagOpts = Omit<SpawnOpts, "brief">;

/** A provider's declared trust dialog: the pattern that detects it and the
 * input that confirms it. `confirmInput: null` means the app must NOT
 * auto-confirm (a bare Enter can land on the cancel button), so the prompt is
 * detected and reported but left for a human. */
export type TrustPromptDecl = { pattern: RegExp; confirmInput: string | null };

export type ProviderDef = {
  id: ProviderId;
  label: string;
  binaryNames: string[];
  /** Declared trust dialog, read generically by pty-registry — never a
   * per-provider branch. Absent = this provider has no such dialog. */
  trustPrompt?: TrustPromptDecl;
  /**
   * Flags only — never the brief. `spawnArgv` appends the brief after
   * these, in the declared form, so the ORDER (brief last, behind `--`
   * for positional providers) is derived once instead of chosen by hand
   * in five places. Must never emit a bare `--` itself: that would turn
   * every later token into an operand.
   */
  buildArgs: (opts: ProviderFlagOpts) => string[];
  /** Declared capabilities — report discovery is DERIVED from this
   * (`deriveReportDiscovery`), never chosen ad hoc in buildArgs / tips. */
  capacity: ProviderCapacity;
  /** DESIGN-BACKLOG.md item 57 ponto 13 — real, current install command
   * per provider (confirmed live against each provider's own docs/npm
   * package, `windows` variant confirmed 2026-09-03): `binary_not_found`
   * surfaces this to the renderer so it can offer a pre-filled (never
   * auto-run) terminal. `null` for `bash` — always resolves via $SHELL/
   * ComSpec, never "not installed". */
  installCommand: InstallCommand | null;
  /**
   * O PROBE DE PRONTIDÃO declarado por este provider (task 1777060e): como saber
   * que ele está PRONTO, e não só instalado. Ausente/`null` = não declarado, e a
   * disponibilidade responde `unknown` — nunca `ready` por otimismo. Só o
   * provider DINÂMICO declara (é dado do spec); os nativos não declaram nada
   * hoje, e por isso aparecem como `unknown`.
   */
  readiness?: ReadinessProbe | null;
  /**
   * A3c (P5): o MECANISMO que muda a pasta de config/login desta CLI —
   * `{ env }` ou `{ flag }` — para o Stellar apontá-la à pasta do PERFIL quando
   * o perfil é `isolated` (BACKEND_V1.md §5.5). AUSENTE = o CLI não separa por
   * perfil; nesse caso o card abre com as pastas do sistema e AVISA. É dado da
   * declaração, nunca um `if (provider === …)`.
   */
  configHome?: ConfigHomeDecl;
};

/**
 * A declaração dos seis nativos — o seed CONGELADO do registro.
 *
 * Não é a lista que o resto do app lê: quem lê é `PROVIDERS`, logo abaixo,
 * que começa com estes e ganha os dinâmicos em runtime. Separar as duas
 * existe para uma coisa só: um provider dinâmico (config do usuário) nunca
 * pode substituir nem remover um nativo — colidiu, o nativo ganha, e o
 * dinâmico é reportado como `skipped` (ver `registerDynamicProviders`).
 */
const NATIVE_PROVIDERS: readonly ProviderDef[] = [
  // Bash has no system-prompt injection flag and no provider-specific MCP
  // registration. A manually launched agent inherits AGENT_CANVAS_* and
  // `acbridge` on PATH, but the shell cannot turn that into MCP or show
  // ACBRIDGE_HINT by itself — DESIGN-BACKLOG.md §2.1 point 3. Coverage
  // chosen: human tip via `decideBashCardDiscovery` (pty-registry), not a
  // binary wrapper (forbidden process-name detection) and not --rcfile
  // (would risk clobbering the user's shell rc). Point 4 nested identity
  // stays a known gap — `acbridge claim-card` declined (no cheap handshake).
  {
    id: "bash",
    label: "Bash",
    binaryNames: [],
    buildArgs: () => [],
    installCommand: null,
    capacity: {
      role: "shell",
      systemPrompt: { mechanism: "none" },
      mcp: { mechanism: "none" },
      acbridgeOnPath: true,
      effort: { mechanism: "none", reason: "shell" },
      model: { mechanism: "none", reason: "shell" },
      // Um shell não tem sessão de agente para retomar nem id para impor.
      session: { canImposeSessionId: false },
      delivery: { briefMechanism: "none", submitStartedPattern: undefined },
    },
  },
  {
    id: "claude",
    label: "Claude",
    binaryNames: ["claude"],
    // MEDIDO (A3c, 2026-10-04): CLAUDE_CONFIG_DIR aparece 80× no binário
    // v2.1.289 e é o que muda a pasta de config/login do Claude.
    configHome: { env: "CLAUDE_CONFIG_DIR" },
    // The dialog's default focus is Cancel, so a bare Enter cancels the launch
    // (exit 1): detected, but never auto-confirmed.
    trustPrompt: { pattern: /Quick safety check: Is this a project you created or one you trust\?/, confirmInput: null },
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "append-system-prompt" },
      // MEDIDO: `-p <prompt> --output-format json` → objeto JSON, texto em
      // `.result` (ver `OneShotCapability`).
      oneShot: { mechanism: "argv", args: ["-p", "{prompt}", "--output-format", "json"], result: "stdout-json" },
      // CARD HEALTH — measured from a real claude card screen: its footer
      // carries `[███] 72% 720k/1m | 5h [...] …`. The `720k/1m` pair IS the
      // context-window fill, and the CLI prints BOTH numbers — so the window is
      // read from the screen, never hard-coded, and the bar's own `72%`
      // corroborates it. The warn fraction (0.7) is a declared decision: 70% of
      // the window is "little headroom" for handing the card more work.
      health: {
        context: {
          // Used/window bar: groups 1/2 = used, groups 3/4 = window. Requiring
          // the slash keeps the spinner's `↓ 1.2k tokens` (turn volume) out.
          pattern: /([\d.]+)([km])\s*\/\s*([\d.]+)([km])/i,
          warnFraction: 0.7,
          source: "claude status-bar context fill (used/window)",
        },
      },
      mcp: { mechanism: "ephemeral-flag" },
      acbridgeOnPath: true,
      // Range re-measured 2026-09-12 against `claude --help` (v2.1.269) —
      // the full evidence and decision writeup live in the
      // `EffortCapability` comment above.
      effort: { mechanism: "flag", flag: "--effort", values: ["low", "medium", "high", "xhigh", "max"] },
      model: { mechanism: "flag", flag: "--model" },
      // Duas flags distintas, medido 2026-09-13: `--resume` só RETOMA uma
      // sessão que já existe; `--session-id` CRIA com o UUID do Stellar —
      // é por isso que claude pode impor, e é o caso que a declaração
      // precisa distinguir (cursor usa uma só para os dois papéis).
      session: {
        canImposeSessionId: true,
        resumeFlag: "--resume",
        imposeFlag: "--session-id",
        continueFlag: "--continue",
        // O cwd É o nome do diretório do projeto — daí `cwd: root`.
        store: {
          kind: "files",
          root: "~/.claude/projects/{cwd:dashes}",
          pattern: "*.jsonl",
          id: { from: "fileName", strip: ".jsonl" },
          cwd: { from: "root" },
          time: { from: "mtime" },
          read: { exists: "{id}.jsonl", content: { minBytes: MIN_CONTENT_BYTES } },
        },
      },
      delivery: {
        briefMechanism: "positional",
        // MEDIDO AO VIVO (2026-10-05, board do dono, Claude Code v2.1.289): a
        // TUI fecha o rodapé com uma linha de SPINNER, e é ela o único sinal de
        // "o turno começou". Amostras reais colhidas de um card claude trabalhando
        // (`read_card`):
        //   `✶ Drizzling… (6m 58s · ↓ 34.5k tokens)`
        //   `✽ Drizzling… (7m 13s · ↓ 36.1k tokens)`
        // O verbo é ALEATÓRIO (a lista antiga de verbos fixos — Working, Thinking,
        // Swooping… — nunca cobria o que a TUI de hoje sorteia, e por isso o
        // veredito caía em `unknown` para mensagem que chegou); o que é estável é
        // o GLIFO de spinner + gerúndio + `…`. `esc to interrupt` e a lista de
        // verbos MEDIDA antes continuam na união: versões/configurações que os
        // mostram seguem casando, e a nova alternativa só ACRESCENTA recall — a
        // polaridade (evidência positiva) não muda.
        submitStartedPattern: /(?:esc to interrupt)|(?:[✢✣✤✥✦✧✩✪✫✬✭✮✯✰✱✲✳✴✵✶✷✸✹✺✻✼✽✾✿]\s*[A-Z][a-z]+…)|(?:\b(?:Working|Thinking|Generating|Calculating|Swooping|Finagling|Cogitat(?:ed|ing)?|Moseying|Slithering)\b)/i,
        // O hook `Stop` EFÊMERO que o `buildArgs` acima instala (`--settings`
        // → `acbridge turn-complete`): o sinal chega NOMEADO por IPC
        // (`pty:turn-complete`), não por leitura de tela.
        turnEnd: { mechanism: "hook" },
      },
    },
    installCommand: {
      posix: "npm install -g @anthropic-ai/claude-code",
      windows: "npm install -g @anthropic-ai/claude-code",
    },
    // Item 18 do sticky (2026-09-20) — NÃO adiciona uma flag de trust
    // aqui porque não existe uma para adicionar. Medido contra `claude
    // --help` (2.1.278): nenhuma flag pré-aprova o cwd do spawn para o
    // "Quick safety check" (workspace trust dialog) — `--add-dir` só
    // adiciona diretórios extras ao workspace já em sessão,
    // `--dangerously-skip-permissions`/`--permission-mode` só afetam
    // permissão de FERRAMENTA, checagem separada da checagem de trust.
    // Medido também no bundle instalado (`strings` sobre
    // `~/.local/share/claude/versions/2.1.278`): a checagem real
    // (`jSe`, minificado) lê, em ordem, `CLAUDE_CODE_SANDBOXED` (env var
    // que bypassa a checagem para QUALQUER diretório do processo, não só
    // este cwd) e depois `projects[cwd].hasTrustDialogAccepted`
    // persistido no `~/.claude.json` GLOBAL do usuário (mecanismo que o
    // próprio CLI recomenda na sua mensagem de erro para uso
    // não-interativo). Nenhum dos dois é apropriado para `buildArgs`
    // pré-aprovar por spawn: o primeiro é grande demais (bypass
    // permanente, todo diretório), o segundo escreve em estado global
    // fora deste par de arquivos e automatizaria em silêncio a decisão
    // de segurança que o diálogo existe para exigir de um humano. A
    // correção real fica em pty-registry.ts's `detectTrustPrompt` —
    // reconhecer o diálogo no scrollback e sinalizar o card como
    // aguardando consentimento (`onTrustPromptPending`), não bypassá-lo.
    buildArgs: ({ resumeId, continueLast, imposedSessionId, model, effort, systemPrompt, mcpUrl }) => {
      const args: string[] = [];
      // Restore vs impose are different flags (measured): `--resume`
      // needs a session that already exists; `--session-id` creates one
      // with the UUID Stellar generated. Never both.
      if (resumeId) args.push("--resume", resumeId);
      else if (imposedSessionId) args.push("--session-id", imposedSessionId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      // DESIGN-BACKLOG.md §2.1, 2026-09-09 — real cost to the repo's owner
      // ("a sessão era um opus medium... voltei como high e custou
      // muito"): confirmed via `claude --help` (not assumed, see
      // `SpawnOpts.effort`'s own doc comment) that this flag is real —
      // `--effort <level>` (low/medium/high/xhigh/max). Sent whenever the
      // card has one, same as `model` right above — the two are always
      // read from the same `spawnOpts` object built once in
      // useTerminal.ts, so neither ever reaches here without the other.
      if (effort) args.push("--effort", effort);
      // This is a real Claude CLI flag (`claude --help`). The task prompt
      // and the environment hint are additive; neither should hide the
      // other, so compose them before passing the single appended block.
      args.push("--append-system-prompt", composeSystemPrompt(systemPrompt));
      // Ephemeral registration (DESIGN-BACKLOG.md item 21, ponto 9) — a
      // spawn-scoped `--mcp-config` flag, not a written .mcp.json. Never
      // touches the project's own MCP config, never persists past this
      // one process. `--strict-mcp-config` is deliberately NOT set here —
      // this should ADD to whatever the user's own project already
      // configures, not replace it.
      //
      // `--mcp-config <configs...>` is VARIADIC (`claude --help`): it
      // keeps eating non-option tokens. The brief used to be pushed right
      // here and was read as a second config file (card 471, 2026-09-13,
      // `ENAMETOOLONG`). The brief now arrives via `spawnArgv`, behind
      // `--`, after every flag — nothing positional may follow this.
      if (mcpUrl) {
        args.push(
          "--mcp-config",
          JSON.stringify({ mcpServers: { stellar: { type: "http", url: mcpUrl } } }),
        );
      }
      // Prototipo (2026-09-06) — "unificar detecção de turno" pedido pelo
      // usuário: `isActive` (useTerminal.ts) hoje é só uma aproximação por
      // silêncio de bytes (900ms sem nada = "parou"), documentada como tal
      // no próprio código — faz a barra de atividade sumir mesmo com o
      // agente genuinamente ainda trabalhando (pensando, chamando
      // ferramenta), sem nenhum marcador real de fim de turno. `claude`
      // suporta hooks de verdade — `--settings` (confirmado ao vivo,
      // aceita um JSON string direto, não só path de arquivo) registra um
      // hook `Stop` EFÊMERO, aditivo igual o `--mcp-config` acima (nunca
      // toca `~/.claude/settings.json` nem o `.claude/settings.json` do
      // projeto — sem `--strict-mcp-config` equivalente aqui porque
      // `--settings` já é descrito como "additional settings", soma em
      // vez de substituir). O comando do hook é só `acbridge
      // turn-complete`, sem argumento nenhum — `acbridge` já lê seu
      // próprio `AGENT_CANVAS_CARD_ID` do ambiente (pty-registry.ts's
      // `spawn()` injeta isso em todo processo spawnado), mesmo auto-fill
      // que `report`/`send` já usam. Sinal REAL de fim de turno, não mais
      // heurística — `useTerminal.ts` usa isto pra decidir quando
      // `isActive` vira false, só pra este provider.
      args.push(
        "--settings",
        JSON.stringify({
          hooks: { Stop: [{ hooks: [{ type: "command", command: "acbridge turn-complete" }] }] },
        }),
      );
      return args;
    },
  },
  {
    id: "codex",
    label: "Codex",
    binaryNames: ["codex"],
    // CODEX_HOME é o env documentado do Codex para a pasta de config/login
    // (o binário instalado é um wrapper node; a doc é a medição).
    configHome: { env: "CODEX_HOME" },
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "developer_instructions" },
      // MEDIDO: `exec <prompt> -o <arquivo>` → o texto final cai no arquivo
      // (o `exec` do codex lê stdin quando ele é pipe, daí o stdin fechado).
      oneShot: { mechanism: "argv", args: ["exec", "{prompt}", "-o", "{outFile}"], result: "out-file" },
      mcp: { mechanism: "ephemeral-flag" },
      acbridgeOnPath: true,
      // NOT "codex has no effort flag" — that was never measured. What is
      // true: no effort flag was ever measured for codex's CLI, and
      // buildArgs has never sent one. The refusal sentence derives from
      // exactly that (reason: "unmeasured") — measuring `codex --help`
      // for a real flag would upgrade this to a flag + range.
      effort: { mechanism: "none", reason: "unmeasured" },
      model: { mechanism: "flag", flag: "-m" },
      // Sem flags aqui de propósito: o `resume` do codex é SUBCOMANDO
      // (`resume <id>` / `resume --last`), não flag — uma declaração
      // flag-shaped não o expressa, e inventar `--resume` para ele seria
      // declarar uma medição que não existe. O que o app de fato lê desta
      // declaração é `canImposeSessionId: false` (medido 2026-09-13: codex
      // recusa um id desconhecido). O buildArgs à mão abaixo continua sendo
      // a implementação.
      session: {
        canImposeSessionId: false,
        // O `resume` do codex é SUBCOMANDO (`resume <id>` / `resume --last`),
        // e o buildArgs à mão abaixo o emite — então esta CLI RETOMA por um id
        // observado. Declarado aqui porque nenhuma flag o expressa (medido
        // 2026-10-03, task 11914cc7: sem isto o codex seria lido como NÃO
        // retomável e o id observado ficaria `null` em silêncio).
        resumeById: true,
        // Medido 2026-09-13 (task c1064d95): `session_index.jsonl` está
        // INCOMPLETO nesta máquina (4 linhas para dezenas de rollouts) — a
        // descoberta lê o próprio rollout, nunca o índice.
        store: {
          kind: "files",
          root: "~/.codex/sessions",
          pattern: "*/*/*/rollout-*.jsonl",
          // O `type === "session_meta"` que a versão à mão checava não virou
          // campo: quem identifica a linha é o CAMINHO (`payload.session_id`
          // / `payload.cwd`), que só existe nela. Medido: 33/33 rollouts
          // desta máquina têm `session_meta` como 1ª linha, com os dois.
          id: { from: "jsonLine", path: ["payload", "session_id"] },
          cwd: { from: "jsonLine", path: ["payload", "cwd"] },
          time: { from: "mtime" },
          // Na LEITURA o id é procurado no NOME do rollout — o que a versão
          // à mão fazia (`name.includes(resumeId)`).
          read: { exists: "*/*/*/rollout-*{id}*.jsonl", content: { minBytes: MIN_CONTENT_BYTES } },
        },
      },
      delivery: {
        briefMechanism: "positional",
        submitStartedPattern: undefined,
        // MEDIDO (o padrão que vivia no renderer, `TURN_END_PATTERNS`): a TUI
        // fecha o turno com `Worked for …` — `Worked for 1m 06s`,
        // `Worked for 8m 0s`. O que separa este marcador do trabalho em
        // andamento é o VERBO, não a linha: o mesmo TUI imprime
        // `Thought for N seconds` a CADA passo, e é isso que impede um
        // match no meio do turno.
        turnEnd: { mechanism: "screen", pattern: /Worked for (?:\d+h\s*)?(?:\d+m\s*)?\d+s/ },
      },
    },
    installCommand: {
      posix: "npm install -g @openai/codex",
      windows: "npm install -g @openai/codex",
    },
    // Codex's resume is a subcommand, must come before any other flag.
    // Codex has no dedicated system-prompt flag, but its real `-c
    // key=value` CLI option (confirmed via `codex --help`) accepts the
    // official `developer_instructions` config key. JSON.stringify produces
    // a valid TOML basic string, including for prompts with quotes/newlines.
    // Variadic audit (`codex --help`, 2026-09-13): only `-i, --image
    // <FILE>...` is variadic, and it is not used here — `-c` is
    // repeatable, one value each. The brief is appended by `spawnArgv`
    // behind `--` (clap honours it, measured) so this stays true even if
    // a variadic flag is added later.
    buildArgs: ({ resumeId, continueLast, model, systemPrompt, mcpUrl }) => {
      const args: string[] = [];
      if (resumeId) args.push("resume", resumeId);
      else if (continueLast) args.push("resume", "--last");
      if (model) args.push("-m", model);
      args.push(
        "-c",
        `developer_instructions=${JSON.stringify(composeSystemPrompt(systemPrompt))}`,
      );
      if (mcpUrl) args.push("-c", `mcp_servers.stellar.url=${mcpUrl}`);
      return args;
    },
  },
  // `cursor` on PATH is usually the IDE launcher; the agent CLI is a
  // separate binary. DESIGN-BACKLOG.md item 57 ponto 13 — confirmed live
  // against cursor.com/docs/cli/installation (2026-08-29) that the
  // installed binary is now named `agent`, not `cursor-agent` — Cursor
  // renamed it at some point after this list was first written ("older
  // articles still use the longer name," per their own docs). Tries the
  // current name first, falls back to the legacy one for an install that
  // predates the rename — same `which()` semantics as every other
  // multi-name lookup already in this file.
  {
    id: "cursor",
    label: "Cursor",
    binaryNames: ["cursor-agent", "agent"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "none" },
      // MEDIDO 2026-10-01 (task 34887bbc), cursor-agent v2026.09.18-9a7762b:
      // `-p/--print` + `--output-format json` estão no `--help`, e uma
      // EXECUÇÃO real devolveu JSON com o texto em `.result`. Antes disto o
      // comentário dizia "mesmas flags do claude" sem medição (R4 de
      // efc5b6fd) — ver `tests/unit/fixtures/one-shot/`.
      oneShot: { mechanism: "argv", args: ["-p", "{prompt}", "--output-format", "json"], result: "stdout-json" },
      // Global ~/.cursor/mcp.json — headless `agent` DOES read it
      // (measured 2026-09-12). Why no cursor card ever saw the tools
      // anyway, and the fix (`env` interpolation in the entry, because
      // cursor whitelists the MCP child's environment): measured
      // 2026-09-13, documented in mcp-registration.ts. Still insufficient
      // alone for report DISCOVERY (no system-prompt flag) — see
      // deriveReportDiscovery / capacity-contract header.
      // `urlSyntax`: MEDIDO (task f7a2ac84 R4) — `agent mcp list-tools stellar`
      // contra o servidor real devolveu 53 tools com `${env:...}` no url.
      mcp: { mechanism: "global-config", urlSyntax: "dollar-env" },
      acbridgeOnPath: true,
      // Same honest "unmeasured" as codex above: no effort flag was ever
      // measured for cursor's `agent` CLI, and buildArgs has never sent
      // one. Do not upgrade this to "no-flag" without measuring.
      effort: { mechanism: "none", reason: "unmeasured" },
      model: { mechanism: "flag", flag: "--model" },
      // DUAS flags, e não uma (medido 2026-09-22, cursor-agent 2026.09.18):
      //
      //   `--resume [chatId]`  -> "Select a session to resume" (RETOMAR)
      //   `--new-session-id`   -> exige UUIDv4, e é MUTUAMENTE EXCLUSIVA com
      //                           `--resume`/`--continue`: é a de IMPOR.
      //
      // Como isto foi medido, porque importa: a flag de imposição NÃO aparece
      // no `--help` (por isso a medição por help, que basta para o cline, não
      // bastava aqui). Medido EXECUTANDO a CLI instalada:
      //   `cursor-agent --new-session-id nao-e-uuid -p x` ->
      //     `Error: Invalid --new-session-id "nao-e-uuid": expected a UUIDv4.`
      //   `cursor-agent --new-session-id <uuid> --resume <uuid> -p x` ->
      //     `Error: --new-session-id cannot be combined with --resume or --continue.`
      // e confirmado no parser do próprio CLI (`.../versions/<ver>/7021.index.js`).
      //
      // A declaração anterior dizia `imposeFlag: "--resume"` com a frase
      // "medido: `--resume <uuid>` cria a sessão quando o id ainda não existe"
      // (medição de 2026-09-13, OUTRA versão da CLI). Hoje existe uma flag cujo
      // CONTRATO é criar com o id escolhido — e `randomUUID()` do Stellar é v4,
      // que é exatamente o que ela exige. O que NÃO medi: se `--resume` com um
      // id desconhecido ainda cria na versão de hoje (exigiria uma execução
      // autenticada, gastando quota e escrevendo sessão no store do dono).
      session: {
        canImposeSessionId: true,
        resumeFlag: "--resume",
        imposeFlag: "--new-session-id",
        continueFlag: "--continue",
        store: {
          kind: "files",
          root: "~/.cursor/chats",
          pattern: "*/*/meta.json",
          id: { from: "dirName" },
          cwd: { from: "json", path: ["cwd"] },
          time: { from: "json", path: ["createdAtMs"] },
          // O sinal de conteúdo é a EXISTÊNCIA de `store.db`, não tamanho:
          // medido que uma sessão vazia já tem `meta.json` com 138-169
          // bytes, então um limiar de bytes nunca reprovava nada. O par
          // exists/hasContent existe porque "o diretório da sessão existe" e
          // "a conversa começou" são perguntas diferentes.
          read: { exists: "*/{id}", content: { file: "store.db" } },
        },
      },
      delivery: {
        briefMechanism: "positional",
        submitStartedPattern: /[\u2800-\u28FF]\s*(?:Running|Reading|Grepping)\b/i,
        // Live 2026-09-14 (card 513): mid-turn send → box `follow-ups` with
        // footer `enter steer · ↑ select/edit · esc cancel`. First Enter
        // parks; second Enter steers into the live turn. get_delivery used
        // to call that park `delivered` (Running neighborhood shifted when
        // the box appeared). Antigravity/claude measured same day: no
        // equivalent box — do not copy this declaration without measuring.
        midTurnQueue: {
          parkedPattern: /\bfollow-ups\b[\s\S]*?\benter\s+steer\b/i,
          steerKey: "\r",
        },
      },
    },
    // Windows confirmado contra cursor.com/docs/cli/installation
    // (2026-09-03) — instalador PowerShell nativo, mesmo endpoint com
    // um query param a mais, sem WSL.
    installCommand: {
      posix: "curl https://cursor.com/install -fsS | bash",
      windows: "irm 'https://cursor.com/install?win32=true' | iex",
    },
    // Sem flag de system-prompt: `prompt` é a entrada do usuário, não um
    // bloco de instruções do sistema. E, ao contrário de claude/codex acima,
    // sem flag efêmera de registro de MCP: a CLI do Cursor só descobre
    // servidor MCP por `.cursor/mcp.json` escrito em disco (do projeto ou
    // global). Escrever no `.cursor/mcp.json` DO PROJETO a cada spawn
    // continua fora de cogitação — é efeito colateral no repositório do
    // usuário. O que mudou (2026-09-01, a pedido): o registro passou a
    // acontecer uma vez só, no config GLOBAL do usuário e apontando pro
    // shim stdio, em `mcp-registration.ts` — fora do `buildArgs`, que é
    // por invocação. Por isso não há nada de MCP nos args aqui.
    // Report discovery is DERIVED as scrollback (capacity.systemPrompt
    // none + acbridgeOnPath) — see decideBashCardDiscovery.
    buildArgs: ({ resumeId, continueLast, imposedSessionId, model }) => {
      const args: string[] = [];
      // RETOMAR e IMPOR são flags diferentes (medido 2026-09-22 — ver a nota
      // longa em `capacity.session`, acima): `--resume` escolhe uma sessão
      // existente; quem cria com o id escolhido é `--new-session-id`. Mandar
      // `--resume <uuid novo>` pedia para RETOMAR uma sessão que não existe.
      // O CLI proíbe as duas juntas, então nunca se manda as duas.
      if (resumeId) args.push("--resume", resumeId);
      else if (imposedSessionId) args.push("--new-session-id", imposedSessionId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      // Positional prompt (`agent [options] [command] [prompt...]`) —
      // measured task 95582065 — is appended by `spawnArgv` behind `--`.
      // Variadic audit (`agent --help`, 2026-09-13): no variadic option;
      // `--add-dir`/`--plugin-dir`/`-H` are repeatable, one value each.
      return args;
    },
  },
  // Pedido ao vivo (2026-08-31) — usuário pediu pra trocar o provider
  // "gemini" por "antigravity": achado ao vivo pesquisando (`gemini`
  // deixou de resolver como CLI própria — a Google aposentou o Gemini
  // CLI e o substituiu pelo Antigravity CLI, um agente de terminal
  // escrito em Go que compartilha motor com o app desktop Antigravity
  // 2.0). Flags confirmadas via busca na documentação real (não
  // adivinhadas): binário `agy`, `--conversation <id>` retoma uma
  // conversa específica por id, `--continue`/`-c` retoma a mais
  // recente, `--model` seleciona o modelo. Sem flag efêmera de
  // registro de MCP por-invocação — confirmado que a única forma é
  // `agy mcp add` (persistente, arquivo `~/.gemini/config/
  // mcp_config.json` ou `.agents/mcp_config.json` por workspace) —
  // Como no cursor logo acima, isso deixou de ser uma não-escolha
  // (2026-09-01, a pedido): `mcp-registration.ts` roda `agy mcp add` uma
  // vez, preguiçosamente, no primeiro spawn de um card antigravity, e
  // aponta pro shim stdio — nunca por spawn, nunca no repositório do
  // usuário. Nada de MCP nos args daqui, que são por invocação.
  {
    id: "antigravity",
    label: "Antigravity",
    binaryNames: ["agy"],
    // A newly spawned card stops on this dialog before reading its brief; the
    // default confirms on Enter.
    trustPrompt: { pattern: /Do you trust the contents of this project\?/, confirmInput: "\r" },
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "none" },
      mcp: { mechanism: "global-config" },
      // MEDIDO 2026-10-01 (task 34887bbc), agy v1.2.14: `-p/--print`
      // ("Run a single prompt non-interactively") + `--output-format json`
      // estão no `--help`, e uma EXECUÇÃO real devolveu JSON com o texto em
      // `.response` (o extrator lê `.result`/`.response`) — ver
      // `tests/unit/fixtures/one-shot/`.
      oneShot: { mechanism: "argv", args: ["-p", "{prompt}", "--output-format", "json"], result: "stdout-json" },
      acbridgeOnPath: true,
      // MEDIDO em runtime 2026-10-01 (task 1c4f3b50), agy v1.2.14: o `--help`
      // (validador GLOBAL) anuncia `low|medium|high|max`, mas a faixa real é
      // POR MODELO. `max` é anunciado e NÃO é honrado por modelo NENHUM — por
      // isso NÃO entra na declaração. A faixa declarada é o conjunto de níveis
      // que a CLI aceita, com uma ressalva que o comentário de
      // `EffortCapability` acima registra: `medium` só é honrado por modelo
      // cujo NOME carrega o nível (o default `gemini-3.1-pro`, sem `--model`,
      // recusa `medium`). Evidência: tests/unit/fixtures/antigravity-effort/.
      effort: { mechanism: "flag", flag: "--effort", values: ["low", "medium", "high"] },
      model: { mechanism: "flag", flag: "--model" },
      // Não impõe (medido: ignora um id desconhecido e cunha o seu).
      session: {
        canImposeSessionId: false,
        resumeFlag: "--conversation",
        continueFlag: "--continue",
        // O cwd mora num blob protobuf (campo length-delimited com uma URI
        // `file://<cwd>`) — o ÚNICO caso especial NOMEADO da linguagem, e o
        // motivo está em `session-store-spec.ts`.
        store: {
          kind: "files",
          root: "~/.gemini/antigravity-cli/conversations",
          pattern: "*.db",
          id: { from: "fileName", strip: ".db" },
          cwd: { from: "binaryWorkspaceUri" },
          time: { from: "mtime" },
          read: { exists: "{id}.db", content: { minBytes: MIN_CONTENT_BYTES } },
        },
      },
      delivery: {
        briefMechanism: "flag",
        briefFlag: "-i",
        submitStartedPattern: /[\u2800-\u28FF]\s*(Generating|Reviewing Initial Input)\.\.\./i,
        // Measured on live cards (agy 1.3.1): the footer SWAPS with the state — busy shows
        // `esc to cancel` (plus `Tip: Press esc to interrupt generation.`),
        // idle shows `? for shortcuts` and never both. No "Worked for" line
        // exists, so the idle footer is the end marker.
        screenTurn: {
          working: /esc to cancel|Press esc to interrupt generation/,
          ended: /\? for shortcuts/,
        },
      },
    },
    // Windows confirmado contra a documentação real do Antigravity CLI
    // (2026-09-03) — instalador PowerShell nativo, sem WSL (há também uma
    // variante `.cmd` pro prompt puro, mas o PowerShell já cobre o caso
    // padrão sem precisar de um segundo comando por SO).
    installCommand: {
      posix: "curl -fsSL https://antigravity.google/cli/install.sh | bash",
      windows: "irm https://antigravity.google/cli/install.ps1 | iex",
    },
    // Sem flag de system-prompt: `--prompt` é o modo de entrada inicial do
    // usuário, não um canal para acrescentar contexto de ambiente.
    // Report discovery → scrollback (derived). MCP registered via
    // `agy mcp add` in mcp-registration.ts (global-config).
    // No `low|medium|high` guard HERE on purpose (2026-09-10,
    // DESIGN-BACKLOG.md §2.1; range re-measured 2026-09-12) — the real
    // refusal for an out-of-range antigravity effort lives centrally in
    // message-bus.ts's `spawn_agent` handler, via `decideSpawnProfile`
    // (spawn-profile-decision.ts) reading this provider's own
    // `capacity.effort` declaration — the one place that validates
    // BEFORE any card/process gets created. By the time `buildArgs`
    // runs here, that gate has already passed — duplicating the check
    // would just be a second copy of the same list
    // to keep in sync, not a second layer of real safety (`effort` isn't
    // renderer-writable outside that one path — see providers.ts's
    // `SpawnOpts.effort` doc comment).
    buildArgs: ({ resumeId, continueLast, model, effort }) => {
      const args: string[] = [];
      if (resumeId) args.push("--conversation", resumeId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      if (effort) args.push("--effort", effort);
      // Interactive prompt only: positional is refused (exit 2); `-p` is
      // headless and exits. Measured task 95582065. Form (`-i <brief>`)
      // comes from `delivery.briefFlag`, appended by `spawnArgv`. Go
      // `flag` parser (`agy --help`, 2026-09-13): no variadic option at
      // all, and a flag-carried brief cannot be swallowed anyway.
      return args;
    },
  },
];

/**
 * O REGISTRO VIVO de providers — nativos + dinâmicos (2026-09-19).
 *
 * É esta lista (não `NATIVE_PROVIDERS`) que `providerById` /
 * `providerCapacity` / `checkAgentAvailability` varrem, e é por isso que
 * registrar um provider em runtime basta para ele funcionar no
 * `resolveSpawn`/`spawnArgv` inteiros: nada abaixo tem caso especial por
 * id, tudo passa pela declaração de capacidade daquele provider.
 *
 * O que NÃO é dinâmico, de propósito: os `buildArgs` escritos à mão dos
 * seis nativos (com comentários de medição que valem mais do que
 * qualquer generalização) e a ordem dos cards na UI, que é do renderer.
 */
export const PROVIDERS: ProviderDef[] = [...NATIVE_PROVIDERS];

/** Ids nativos capturados ANTES de qualquer merge — a muralha que impede
 * um arquivo de config do usuário de sobrescrever claude/codex/… (ver
 * `registerDynamicProviders`). */
const NATIVE_PROVIDER_ID_SET: ReadonlySet<string> = new Set(NATIVE_PROVIDERS.map((p) => p.id));

export type RegisterProvidersResult = {
  /** Registrados agora (ou re-registrados — um reload substitui o def
   * anterior do MESMO id dinâmico, nunca o do nativo). */
  registered: ProviderId[];
  /** Recusados por colisão com um id nativo: o nativo sempre ganha. */
  skipped: ProviderId[];
  /** DERRUBADOS do registro vivo nesta carga (só com `pruneMissing`): ids
   * dinâmicos que estavam registrados e não vieram mais. Um id nativo
   * nunca aparece aqui. */
  removed: ProviderId[];
};

/**
 * A MEMÓRIA do diff: ids que ESTE módulo registrou pelo caminho dinâmico.
 *
 * Nativo nunca entra aqui — `registerDynamicProviders` os recusa antes de
 * tocar em `PROVIDERS` — então "está neste set" é exatamente "esta entrada
 * foi criada pelo merge dinâmico". É o que dá ao unregister um alvo exato:
 * sem isto, "tirar do registro o que não está mais no arquivo" não teria
 * como distinguir um provider dinâmico removido de um nativo.
 *
 * Módulo-level, como `PROVIDERS` — é o mesmo registro, com a mesma vida.
 */
const dynamicProviderIds = new Set<string>();

/**
 * Registra providers dinâmicos no registro vivo. Idempotente por id: uma
 * segunda chamada com o mesmo id dinâmico SUBSTITUI o def anterior (é
 * como um reload depois de editar o arquivo de config funciona), sem
 * nunca tocar num nativo.
 *
 * `pruneMissing` (2026-09-19, follow-up da G6) — o que faz a REMOÇÃO
 * funcionar sem reiniciar. MEDIDO antes disto: tirar um provider pelo
 * formulário reescrevia o arquivo e ele continuava em `checkAvailability`
 * (e portanto nos pickers e no `resolveSpawn`) até o app reiniciar, porque
 * a versão anterior só sabia fazer push/replace. Com a flag ligada, a
 * lista `defs` é tratada como a lista EFETIVA COMPLETA daquela carga: id
 * dinâmico que não veio mais é removido de `PROVIDERS`.
 *
 * Desligada por padrão de propósito: o nome desta função é "registre
 * estes", e um chamador com lista parcial não pode perder entradas por
 * engano. Quem SABE que a lista é completa é o loader
 * (`providers-dynamic.ts`), e é ele que liga.
 *
 * Não faz I/O e não valida spec — quem faz as duas coisas é
 * `providers-dynamic.ts`, que é a casca deste módulo (mesma divisão
 * decisão × efeito do resto do repo).
 */
export function registerDynamicProviders(
  defs: readonly ProviderDef[],
  opts: { pruneMissing?: boolean } = {},
): RegisterProvidersResult {
  const registered: ProviderId[] = [];
  const skipped: ProviderId[] = [];
  const nextIds = new Set<ProviderId>();
  for (const def of defs) {
    if (NATIVE_PROVIDER_ID_SET.has(def.id)) {
      skipped.push(def.id);
      continue;
    }
    nextIds.add(def.id);
    // Fila de mid-turn MEDIDA pelo app (Ver MEASURED_MID_TURN_QUEUES): entra
    // no REGISTRO, não no spec — o def vivo e `providerCapacity` concordam, e
    // um override do usuário que já declare a fila dele nunca é sobrescrito.
    const measuredQueue = MEASURED_MID_TURN_QUEUES[def.id];
    const measuredHealth = MEASURED_HEALTH[def.id];
    const needsQueue = !!measuredQueue && !def.capacity.delivery.midTurnQueue;
    // Same rule as the queue: only when the provider did not declare its own
    // health, and into the REGISTRY — the spec/JSON and the round-trip are
    // untouched.
    const needsHealth = !!measuredHealth && !def.capacity.health;
    // Same rule for the screen turn state: only when the provider did not
    // declare its own, and into the REGISTRY.
    const measuredScreenTurn = MEASURED_SCREEN_TURNS[def.id];
    const needsScreenTurn = !!measuredScreenTurn && !def.capacity.delivery.screenTurn;
    const resolved =
      needsQueue || needsHealth || needsScreenTurn
        ? {
            ...def,
            capacity: {
              ...def.capacity,
              ...(needsQueue || needsScreenTurn
                ? {
                    delivery: {
                      ...def.capacity.delivery,
                      ...(needsQueue && measuredQueue ? { midTurnQueue: measuredQueue } : {}),
                      ...(needsScreenTurn && measuredScreenTurn ? { screenTurn: measuredScreenTurn } : {}),
                    },
                  }
                : {}),
              ...(needsHealth && measuredHealth ? { health: measuredHealth } : {}),
            },
          }
        : def;
    const existing = PROVIDERS.findIndex((p) => p.id === def.id);
    if (existing >= 0) PROVIDERS[existing] = resolved;
    else PROVIDERS.push(resolved);
    registered.push(def.id);
  }

  const removed: ProviderId[] = [];
  if (opts.pruneMissing) {
    // Diff contra a carga ANTERIOR (o set), não contra `PROVIDERS`: só o
    // que este caminho registrou pode ser derrubado por este caminho.
    for (const id of [...dynamicProviderIds]) {
      if (nextIds.has(id)) continue;
      dynamicProviderIds.delete(id);
      // Muralha explícita, além do set: nenhum nativo sai daqui nem se
      // algum dia parar no set por engano. O `continue` fica ANTES do
      // splice, e o set já foi limpo acima — o nativo continua no
      // registro e a memória não fica suja.
      if (NATIVE_PROVIDER_ID_SET.has(id)) continue;
      const index = PROVIDERS.findIndex((p) => p.id === id);
      if (index >= 0) PROVIDERS.splice(index, 1);
      removed.push(id);
    }
  }
  for (const id of nextIds) dynamicProviderIds.add(id);
  return { registered, skipped, removed };
}

/** Os ids que hoje existem SÓ porque o caminho dinâmico os registrou —
 * leitura para diagnóstico/teste. Nativo não está aqui. */
export function dynamicProviderIdsSnapshot(): ProviderId[] {
  return [...dynamicProviderIds];
}

/** Providers whose CLI accepts a caller-chosen session id on spawn.
 * Measured 2026-09-13 (task c1064d95) for the natives: only claude and
 * cursor; the other three either refuse an unknown id (`codex`,
 * `opencode`) or ignore it and mint their own (`antigravity`).
 *
 * Derivada, nunca uma segunda lista escrita à mão (2026-09-19): a
 * resposta é do próprio provider (`capacity.session.canImposeSessionId`),
 * então um dinâmico registrado em runtime aparece aqui sem nenhuma
 * edição — era exatamente isto que a lista fechada anterior não
 * conseguia fazer. */
export function imposeSessionIdProviders(): ProviderId[] {
  return PROVIDERS.filter((p) => p.capacity.session.canImposeSessionId).map((p) => p.id);
}

export function canImposeSessionId(providerId: string): boolean {
  return providerById(providerId)?.capacity.session.canImposeSessionId ?? false;
}

/**
 * A CLI ESCREVE um id de sessão em disco que dá para OBSERVAR de fora?
 * (`store` declarado — ver `session-store-spec.ts`.) É a pergunta que decide
 * se a participação pode receber um `session_id`.
 *
 * NÃO confundir com `canImposeSessionId`: aquela pergunta é "aceita um id
 * escolhido pelo Stellar num spawn novo?" (só claude/cursor); esta é "dá para
 * LER o id que a CLI cunhou?" — e é a segunda que responde ao dono (o card
 * commandcode/agy morria e a sessão se perdia). */
export function providerExposesSession(providerId: string | null | undefined): boolean {
  if (!providerId) return false;
  return providerCapacity(providerId)?.session.store !== undefined;
}

/**
 * A CLI RETOMA uma sessão a partir de um id OBSERVADO (não imposto)? Lida da
 * própria declaração `capacity.session` — nunca de uma segunda lista `if
 * (provider === …)`. Verdadeiro quando há QUALQUER mecanismo de retomada:
 * `resumeFlag` (claude/cursor/antigravity/opencode/cline/commandcode), uma
 * flag que cria-ou-retoma (`imposeFlag`), a flag de continuar, ou o
 * `resumeById` que cobre o subcomando do codex. */
export function providerResumesById(providerId: string | null | undefined): boolean {
  if (!providerId) return false;
  const session = providerCapacity(providerId)?.session;
  if (!session) return false;
  return (
    session.resumeFlag !== undefined ||
    session.imposeFlag !== undefined ||
    session.continueFlag !== undefined ||
    session.resumeById === true
  );
}

/**
 * Whether this spawn should generate a fresh UUID and pass it as
 * `imposedSessionId`. Pure: generation stays at the call site
 * (`randomUUID`) so tests do not mock crypto. A restore (`resumeId`)
 * or `--continue` is never an impose.
 */
export function shouldImposeSessionId(
  providerId: string,
  opts: { resumeId?: string; continueLast?: boolean },
): boolean {
  if (opts.resumeId || opts.continueLast) return false;
  return canImposeSessionId(providerId);
}

export function providerById(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

/** The trust dialog this provider declares, or null when it declares none. */
export function providerTrustPrompt(id: string): TrustPromptDecl | null {
  return providerById(id)?.trustPrompt ?? null;
}

export function providerCapacity(id: string): ProviderCapacity | undefined {
  return providerById(id)?.capacity;
}

/** Achado ao vivo, 2026-09-03 — "no Windows não tem bash": não existe
 * jeito de sugerir `installCommand.posix` numa máquina sem bash/curl. */
export function providerInstallCommand(
  id: string,
  platform: NodeJS.Platform = process.platform,
): string | null {
  const cmd = providerById(id)?.installCommand;
  if (!cmd) return null;
  return platform === "win32" ? cmd.windows : cmd.posix;
}

// Extensões que o Windows tenta, em ordem, quando um nome sem extensão é
// "executado" — mesma lista que o próprio shell do Windows usa (variável
// `PATHEXT`, com um fallback caso ela não exista por algum motivo). Sem
// isso, `which(["claude"])` nunca acharia o shim real que `npm install -g`
// cria lá (`claude.cmd`/`claude.ps1`, nunca um `claude` sem extensão) —
// achado ao vivo, 2026-09-03, junto com o problema do bash acima: a
// detecção de binário em si já não dependia de shell nenhum (sempre foi
// busca de arquivo pura em `process.env.PATH`), só faltava tentar as
// extensões certas por SO.
// Extensões que o Windows tenta, em ordem, quando um nome sem extensão é
// "executado" — mesma lista que o próprio shell do Windows usa (variável
// `PATHEXT`, com um fallback caso ela não exista por algum motivo). Sem
// isso, `which(["claude"])` nunca acharia o shim real que `npm install -g`
// cria lá (`claude.cmd`/`claude.ps1`, nunca um `claude` sem extensão) —
// achado ao vivo, 2026-09-03.
const WINDOWS_EXECUTABLE_EXTENSIONS = (process.env.PATHEXT || ".COM;.EXE;.BAT;.CMD;.PS1")
  .split(";")
  .filter(Boolean);

/** Tudo que `which` precisa saber do mundo, injetável para que o
 * comportamento de OUTRA plataforma seja testável nesta — é a única forma
 * honesta de cobrir o caso macOS sem um Mac, e sem fingir um. */
export type WhichOptions = {
  platform?: NodeJS.Platform;
  /** Diretórios a varrer, em ordem. Default: o PATH efetivo do usuário
   * (`user-env.ts`), NÃO `process.env.PATH` — ver o cabeçalho de lá. */
  pathDirs?: string[];
  /** Default: arquivo de verdade com bit de execução. */
  isExecutable?: (candidate: string) => boolean;
  /** Só para o Windows; default: `PATHEXT` do processo. */
  pathExt?: string[];
};

/**
 * Acha um binário por nome, varrendo diretórios — sem shell nenhuma, o
 * que já era verdade aqui antes e continua sendo.
 *
 * O que mudou (2026-09-08): a lista de diretórios deixou de ser
 * `process.env.PATH` cru. Num `.app` aberto pelo Finder no macOS aquele
 * PATH é o mínimo do launchd e não contém nada que o usuário instalou —
 * ver `user-env.ts` para o porquê e para o que entra no lugar.
 *
 * E o teste de candidato deixou de ser `existsSync`: ele dizia "sim" para
 * um DIRETÓRIO chamado `agent` no PATH (o nome primário da CLI do Cursor,
 * nada improvável) e para um arquivo sem bit de execução.
 */
export function which(
  names: string[],
  platformOrOptions: NodeJS.Platform | WhichOptions = {},
): string | null {
  // Assinatura retrocompatível: os chamadores existentes passam a
  // plataforma direto como segundo argumento.
  const opts: WhichOptions =
    typeof platformOrOptions === "string" ? { platform: platformOrOptions } : platformOrOptions;
  const platform = opts.platform ?? process.platform;
  const isExecutable = opts.isExecutable ?? isExecutableFile;
  const dirs = opts.pathDirs ?? effectivePath().split(delimiter).filter(Boolean);
  const extensions = opts.pathExt ?? WINDOWS_EXECUTABLE_EXTENSIONS;
  const candidateNames =
    platform === "win32"
      ? names.flatMap((name) => [name, ...extensions.map((ext) => name + ext)])
      : names;
  for (const name of candidateNames) {
    for (const dir of dirs) {
      const candidate = join(dir, name);
      if (isExecutable(candidate)) return candidate;
    }
  }
  return null;
}

/** Resolves the binary + args to spawn for a provider. `bash` always
 * resolves via $SHELL no POSIX; no Windows não existe `$SHELL`
 * (variável de ambiente é uma convenção só de shells Unix) nem `/bin/
 * bash` — resolve via `ComSpec` (sempre presente, aponta pro `cmd.exe`
 * real), mesma convenção que o próprio Windows/outras ferramentas
 * (ex. VS Code) usam como shell padrão quando nada mais foi escolhido. */
export function resolveSpawn(
  providerId: string,
  opts: SpawnOpts = {},
): { binary: string; args: string[] } | null {
  const provider = providerById(providerId);
  if (!provider) return null;
  if (provider.id === NATIVE_PROVIDER_IDS.bash) {
    if (process.platform === "win32") {
      return { binary: process.env.ComSpec || "C:\\Windows\\System32\\cmd.exe", args: [] };
    }
    // `loginShell()` (user-env.ts) já é a cadeia certa: $SHELL, depois a
    // base de usuário do SO via getpwuid(), e só então um caminho fixo —
    // `/bin/zsh` no macOS, onde é o padrão desde o Catalina, `/bin/sh` no
    // resto, que é o único POSIX obrigatório (`/bin/bash`, o fallback
    // anterior, não existe em toda distro).
    return { binary: loginShell(), args: [] };
  }
  const binary = which(provider.binaryNames);
  if (!binary) return null;
  return { binary, args: spawnArgv(provider, opts) };
}

export type AgentAvailability = {
  id: ProviderId;
  label: string;
  installed: boolean;
  installCommand: string | null;
  /**
   * PRONTO? — e não só instalado (task 1777060e). Quatro respostas, cada uma do
   * tamanho da evidência: `missing` (o binário não resolve), `ready` (o probe
   * DECLARADO respondeu que está pronto), `not-ready` (o probe respondeu que
   * não), `unknown` (instalado e o app não sabe: sem probe declarado, ou o
   * probe não respondeu).
   *
   * POR QUE ISTO EXISTE: medido com o `omp` instalado e sem credencial — o
   * `installed: true` sozinho fazia a tela oferecer o provider, o spawn "dar
   * certo" e o card ficar calado para sempre (`omp -p ...` pendura). Ver
   * `provider-readiness-decision.ts` para a medição inteira.
   */
  readiness: ProviderReadinessState;
  /** O que sustenta o estado (viaja para a tela e para o relato). */
  readinessEvidence: string;
  /** O comando que o HUMANO roda para sair do estado, quando o provider
   *  declara um. `null` = a UI não promete caminho nenhum. */
  readinessHint: string | null;
};

/** Checagem proativa (DESIGN-BACKLOG.md — "aviso antes mesmo de abrir um
 * agente", pedido ao vivo 2026-09-03): roda uma vez, fora do fluxo de
 * spawn de qualquer card, pro Topbar mostrar de cara quais CLIs de agente
 * faltam instalar. `bash` fica de fora — não é uma CLI de agente
 * instalável, é sempre o shell do próprio SO (ver resolveSpawn acima). */
export function checkAgentAvailability(): AgentAvailability[] {
  const now = Date.now();
  return PROVIDERS.filter((p) => p.id !== NATIVE_PROVIDER_IDS.bash).map((p) => {
    const installed = which(p.binaryNames) !== null;
    const probe = p.readiness ?? null;
    // Caminho SÍNCRONO: lê a última resposta do cache e não sonda nada — uma
    // sonda de 0,69s aqui congelaria o main (é `which()`, síncrono). Enquanto
    // não houver resposta, a decisão pura devolve `unknown`.
    const decision = decideProviderReadiness({ installed, probe, result: readinessCache.get(p.id, now) });
    return {
      id: p.id,
      label: p.label,
      installed,
      installCommand: providerInstallCommand(p.id),
      readiness: decision.state,
      readinessEvidence: decision.evidence,
      readinessHint: probe?.hint ?? null,
    };
  });
}

/**
 * SONDA em background os providers cujo probe declarado está vencido (ou nunca
 * rodou), e devolve o que MUDOU de estado.
 *
 * É assíncrona de propósito: o custo medido do probe do `omp` é 0,69s e o
 * caminho de leitura é síncrono. Quem chama (o boot e o handler de
 * `agents:check-availability`, em `index.ts`) recebe os ids que mudaram e usa o
 * MESMO push de disponibilidade que já existe — nenhum canal novo.
 *
 * Nunca imprime credencial: o probe só lê um campo booleano do JSON do próprio
 * tool, e o que sai daqui é o veredito e a razão NOMEADA por ele.
 */
export async function refreshProviderReadiness(
  now: () => number = Date.now,
): Promise<{ changed: ProviderId[]; probed: ProviderId[] }> {
  const changed: ProviderId[] = [];
  const probed: ProviderId[] = [];
  for (const p of PROVIDERS) {
    if (p.id === NATIVE_PROVIDER_IDS.bash) continue;
    const probe = p.readiness ?? null;
    if (probe === null) continue;
    if (!readinessCache.needsRefresh(p.id, now())) continue;
    const binary = which(p.binaryNames);
    if (binary === null) continue;
    const before = checkAgentAvailability().find((row) => row.id === p.id)?.readiness;
    const result = await runReadinessProbe(binary, probe);
    readinessCache.set(p.id, result, now());
    probed.push(p.id);
    const after = checkAgentAvailability().find((row) => row.id === p.id)?.readiness;
    if (after !== before) changed.push(p.id);
  }
  return { changed, probed };
}
