import { delimiter, join } from "node:path";
import { effectivePath, isExecutableFile, loginShell } from "./user-env";

export type ProviderId = "bash" | "claude" | "codex" | "cursor" | "antigravity" | "opencode";

export type SpawnOpts = {
  resumeId?: string;
  /**
   * Fresh UUID generated by Stellar to IMPOSE on a brand-new session.
   * Distinct from `resumeId` (restore an existing session whose file
   * already exists). Measured 2026-09-13 (task c1064d95) against the
   * real CLIs: `claude` accepts `--session-id <uuid>` and creates the
   * session with that id; `cursor` accepts `--resume <uuid>` even when
   * the id does not exist yet and creates the session with it.
   * Never set together with a restore `resumeId`. `codex` /
   * `antigravity` / `opencode` reject or ignore an unknown id — do not
   * set this for them (see `canImposeSessionId`).
   */
  imposedSessionId?: string;
  continueLast?: boolean;
  model?: string;
  systemPrompt?: string;
  /** DESIGN-BACKLOG.md item 21, ponto 9, achado 1 — how many agent-
   * initiated (not human-initiated) spawns led to this one. `undefined`/
   * `0` for every human-triggered spawn (rail, radial menu) — a fresh
   * chain always starts here. Threaded into the process env
   * (AGENT_CANVAS_SPAWN_DEPTH, see pty-registry.ts) so a NEW spawn
   * request from THIS agent reports the right depth, and enforced as a
   * hard cap in message-bus.ts (MAX_SPAWN_DEPTH) before any consent
   * modal even shows. */
  spawnDepth?: number;
  /** Sticky item "spawn_agent effort" (2026-09-03) — Antigravity's CLI
   * requires `--effort` alongside certain models (`--model
   * gemini-3.1-pro` on its own falls back silently to a different model
   * with a warning, never actually running the one asked for). Range
   * re-measured 2026-09-12 against `agy --help` (v1.2.2):
   * `low|medium|high` (was documented as only `low|high`). `model` stays
   * a plain string on purpose (every other provider only ever takes one)
   * — this is additive and provider-specific, `undefined` for every
   * provider whose `buildArgs` doesn't read it.
   *
   * 2026-09-09 (DESIGN-BACKLOG.md §2.1, real cost to the repo's owner) —
   * `claude`'s `buildArgs` below now reads this too: confirmed live via
   * `claude --help` (v2.1.269, re-checked 2026-09-12) that it has its own
   * `--effort <level>` flag, `low|medium|high|xhigh|max` — a wider range
   * than antigravity's. Widened from `"low" | "high"` to plain `string`
   * (review adversarial, same day, achado 2) so a card resumed with a
   * value outside the app's own write-path enum (e.g. claude's `xhigh`)
   * round-trips through here unmolested instead of the type forcing a
   * lossy coercion somewhere upstream — see card-types.ts's
   * `TerminalCardData.effort` doc comment for the full reasoning. */
  effort?: string;
  /** Internal only — never set by the renderer/IPC caller. Injected by
   * `pty-registry.ts::spawn()` from its own closed-over `mcpUrl` so
   * `buildArgs` below can register the MCP server per-provider without
   * every call site needing to know the port. */
  mcpUrl?: string;
  brief?: string;
  /**
   * Task this card was spawned to serve (`spawn_agent({ taskId })` or
   * auto-dispatch). Optional in earnest: spawn without a task stays
   * first-class and this stays unset. Threaded into
   * `AGENT_CANVAS_TASK_ID` (pty-registry.ts) only when present — never a
   * placeholder. Not read by `buildArgs`.
   */
  taskId?: string;
};

// ---------------------------------------------------------------------------
// Capacity contract (DESIGN-BACKLOG.md §0, 2026-09-12)
//
// One declaration per provider — system-prompt injection? MCP registration
// (which mechanism)? acbridge on PATH? — with report-discovery DELIVERY
// derived from that declaration (`deriveReportDiscovery`), not chosen
// case-by-case at call sites. A provider that cannot teach an agent to
// report by any path must fail visibly at spawn (see
// bash-discovery-decision.ts), never silently at report time.
//
// Measurement that shaped this (2026-09-12): Cursor's headless CLI (`agent`)
// DOES read `~/.cursor/mcp.json` — confirmed by pointing HOME at a temp
// dir with a probe server and seeing `agent mcp list` pick it up. The
// global registration, shim binary, and HTTP endpoint can all be healthy
// and `agent mcp list` still say `stellar: ready`, yet live cursor cards
// reported "sem tools Stellar" and never called report. MCP alone is
// therefore declared as a capacity but is NOT treated as a sufficient
// report-discovery path; without a system-prompt flag the derived delivery
// is scrollback (acbridge tip), matching the owner's "flag → scrollback →
// fail spawn" rule.
// ---------------------------------------------------------------------------

/** How (if at all) this provider accepts an injected system/developer prompt. */
export type SystemPromptCapability =
  | { mechanism: "append-system-prompt" }
  | { mechanism: "developer_instructions" }
  | { mechanism: "none" };

/** How the stellar MCP server is registered for this provider. */
export type McpRegistrationCapability =
  | { mechanism: "ephemeral-flag" }
  | { mechanism: "global-config" }
  | { mechanism: "none" };

export type ProviderRole = "agent" | "shell";

export type ProviderCapacity = {
  role: ProviderRole;
  systemPrompt: SystemPromptCapability;
  mcp: McpRegistrationCapability;
  /**
   * Every card gets `binDir` prepended to PATH in `pty-registry.ts`, so
   * this is `true` for every current provider. Declared (not assumed) so
   * derivation reads one field instead of a second handwritten list.
   */
  acbridgeOnPath: boolean;

  /** Como a CLI gerencia instruções (brief e TUI follow-ups) */
  delivery: {
    /** 
     * Como o brief é passado no spawn.
     * 'positional' (claude, codex, cursor) — emitido como `-- <brief>` na
     *   cauda do argv (`spawnArgv`); exige que o parser da CLI honre
     *   `--`, medido para os três (ver `END_OF_OPTIONS`).
     * 'flag' (opencode: --prompt, antigravity: -i)
     * 'none' (bash)
     */
    briefMechanism: "positional" | "flag" | "none";
    briefFlag?: string;
    
    /** 
     * Vocabulário de tela DAQUELE provider indicando o início de um turno após receber input na TUI.
     * Fica undefined se não foi medido (evitando inventar regras) ou não for TUI de agente.
     */
    submitStartedPattern?: RegExp;

    /**
     * Mid-turn holding UI: submit while the agent is busy parks the text
     * instead of injecting it. Measured 2026-09-14 on cursor-agent only
     * (`follow-ups` box + `enter steer` footer). Absent = this provider
     * has no such queue (or it was not measured) — callers must not
     * invent an `if (provider === "cursor")` elsewhere; derive from here.
     */
    midTurnQueue?: {
      /** Screen chrome of the park box (new since the delivery write). */
      parkedPattern: RegExp;
      /**
       * Key that injects the selected parked item into the live turn.
       * Measured cursor: bare Enter. At most ONE press after park — never
       * the unsent-retry loop (owner 2026-09-11: 5× paste → exit 143).
       */
      steerKey: string;
    };
  };
};

/**
 * How an agent learns it must call `report` / `acbridge report`.
 * Derived from `ProviderCapacity` — never stored as a parallel fact.
 */
export type ReportDiscovery =
  | "system_prompt"
  | "scrollback"
  | "not_applicable"
  | "unreachable";

/**
 * Derive report-discovery delivery from a capacity declaration.
 * Order: system-prompt flag → scrollback (if acbridge on PATH) →
 * unreachable (spawn must refuse). Shell cards are not agents.
 */
export function deriveReportDiscovery(capacity: ProviderCapacity): ReportDiscovery {
  if (capacity.role === "shell") return "not_applicable";
  if (capacity.systemPrompt.mechanism !== "none") return "system_prompt";
  if (capacity.acbridgeOnPath) return "scrollback";
  return "unreachable";
}

/**
 * The channel a report is EXPECTED to arrive on for this provider —
 * distinct from `ReportDiscovery`, which is how the agent LEARNS it must
 * report. `mcp` means the `report` tool should be in the agent's catalog
 * (registered either by an ephemeral flag in `buildArgs` or by the
 * persistent config `mcp-registration.ts` writes); `acbridge` means the
 * CLI on PATH is the only path; `unreachable` means neither.
 *
 * Derived, never declared: the same `capacity.mcp` that decides whether
 * `ensureMcpRegistered` acts decides this, so the two cannot disagree.
 * Both channels land in the same row (`promoteReportVerdict` in
 * mcp-server.ts unifies them), which is what lets the agent-facing rule
 * stay a single sentence: if `report` is in your catalog use it,
 * otherwise `acbridge report` with `verdict` inside the JSON. The agent
 * decides at runtime by looking at its own catalog — the derived value
 * here is the expectation, not a promise the transport always kept (see
 * the 2026-09-13 whitelist finding in mcp-registration.ts).
 */
export type ReportChannel = "mcp" | "acbridge" | "unreachable";

export function deriveReportChannel(capacity: ProviderCapacity): ReportChannel {
  if (capacity.mcp.mechanism !== "none") return "mcp";
  if (capacity.acbridgeOnPath) return "acbridge";
  return "unreachable";
}

/**
 * POSIX end-of-options marker. Everything after it is an operand, so a
 * positional brief placed behind it can never be swallowed by a
 * preceding VARIADIC option — the 2026-09-13 boot death (card 471):
 * `claude --mcp-config <json> <brief>` parsed the brief as a second
 * config path (`ENAMETOOLONG`), because `--mcp-config <configs...>` is
 * variadic and eats every following non-option token. It also stops a
 * brief that starts with `-` (a markdown bullet, say) from being read as
 * an unknown option and dropped in silence (measured: `claude --print
 * "-diga"` → "Input must be provided", exit 1; with `--` → answered).
 *
 * Honoured by every positional provider's real parser, measured
 * 2026-09-13: claude (commander, `-- "diga apenas OK"` → OK), cursor
 * `agent` (commander, same probe → OK), codex (clap, `-- --help` did not
 * print help — the token became the PROMPT). A future positional
 * provider whose parser does NOT honour `--` must be measured before
 * being declared positional here.
 *
 * Consequence that shapes `spawnArgv` below: the brief fragment MUST be
 * the argv tail. Any option pushed after `--` would itself become an
 * operand — which is why `buildArgs` no longer sees `brief` at all.
 */
export const END_OF_OPTIONS = "--";

/**
 * Argv fragment implied by `delivery` for a spawn brief. One place —
 * `buildArgs` must not invent a second form (positional vs flag vs
 * none). Empty when there is no brief or the provider cannot take one
 * on argv (`bash`). Positional briefs ride behind `END_OF_OPTIONS`.
 */
export function briefArgvFragment(
  delivery: ProviderCapacity["delivery"],
  brief: string | undefined,
): string[] {
  if (!brief) return [];
  if (delivery.briefMechanism === "positional") return [END_OF_OPTIONS, brief];
  if (delivery.briefMechanism === "flag" && delivery.briefFlag) {
    return [delivery.briefFlag, brief];
  }
  return [];
}

/** Whether `args` actually carry `brief` the way `delivery` declares. */
export function argsCarryDeclaredBrief(
  args: readonly string[],
  delivery: ProviderCapacity["delivery"],
  brief: string,
): boolean {
  const fragment = briefArgvFragment(delivery, brief);
  if (fragment.length === 0) return false;
  for (let i = 0; i <= args.length - fragment.length; i++) {
    if (fragment.every((part, j) => args[i + j] === part)) return true;
  }
  return false;
}

/**
 * Empirical: this provider's spawn argv carries `brief` as declared.
 * Spawn dispatch uses this for `canArgv` so a stale declaration cannot
 * drop the text — the typing fallback still fires.
 */
export function argvCarriesDeclaredBrief(providerId: string, brief: string): boolean {
  const provider = providerById(providerId);
  if (!provider) return false;
  return argsCarryDeclaredBrief(spawnArgv(provider, { brief }), provider.capacity.delivery, brief);
}

/**
 * The full argv for a spawn: the provider's hand-written flags, then the
 * brief in the form `delivery` declares — ALWAYS as the tail. This is the
 * one place that decides WHERE the brief goes; `buildArgs` cannot even
 * read `opts.brief` (see `ProviderDef.buildArgs`'s type), so no provider
 * can put it back in the middle of its flags, where a variadic option
 * would eat it (the `--mcp-config` death, see `END_OF_OPTIONS`).
 */
export function spawnArgv(provider: ProviderDef, opts: SpawnOpts): string[] {
  const { brief, ...flagOpts } = opts;
  return [...provider.buildArgs(flagOpts), ...briefArgvFragment(provider.capacity.delivery, brief)];
}

// DESIGN-BACKLOG.md item 21, ponto 9 — the primary agent-facing interface
// is now the MCP server (mcp-server.ts) for providers that speak MCP;
// acbridge stays as the CLI fallback (see its own header comment). Kept
// short — MCP tool descriptions are self-documenting, this is just a
// nudge to look for them, not a manual.
//
// AGENT-FACING — DO NOT TRANSLATE (DESIGN-BACKLOG.md §2.1 i18n).
// Reader is a model, not a human. English is correct. Listed in
// `src/shared/i18n/agent-facing.ts`. A phase-2 string sweep that pulls
// this into `t()` would change agent behaviour with no test catching it.
export const ACBRIDGE_HINT =
  "You're running inside agent-canvas, a board of cards. If an MCP server " +
  "named `stellar` is connected, prefer its tools (list/send/open/spawn/" +
  "close_card/snapshot/page-text/read_card/card_status/report/read_report — read " +
  "each tool's own description). Otherwise a CLI `acbridge` is on your " +
  "PATH with the same capabilities (`acbridge` with no args prints " +
  "usage). If another card spawned you to do a task, report a structured " +
  "result when you finish it, even if you keep running afterward: if a " +
  "tool named `report` is in your tool catalog, call it; otherwise run " +
  "`acbridge report '<json>'` with `verdict` inside the JSON. Same " +
  "payload, same record either way. Use these only when it genuinely " +
  "helps the task at hand.";

/** The custom prompt describes the task; ACBRIDGE_HINT describes the runtime
 * environment. Keep both, in that order, separated by a blank line so the
 * task remains the first thing the provider sees while the environment hint
 * stays legible as a distinct block. Trimming also makes empty or
 * whitespace-only prompts behave like an omitted prompt instead of creating
 * a separator with no task text around it. */
export function composeSystemPrompt(systemPrompt?: string): string {
  const taskPrompt = systemPrompt?.trim();
  return taskPrompt ? `${taskPrompt}\n\n${ACBRIDGE_HINT}` : ACBRIDGE_HINT;
}

/** Um comando por família de SO — `npm install -g` já é igual nas duas,
 * mas os installers via `curl | bash` (cursor/antigravity) não existem no
 * Windows (achado ao vivo, 2026-09-03: "no Windows não tem bash"), que
 * tem seu próprio instalador PowerShell nativo em cada um desses
 * provedores (confirmado contra a documentação real de cada um). */
type InstallCommand = { posix: string; windows: string };

/** What `buildArgs` gets: every spawn option EXCEPT the brief. */
export type ProviderFlagOpts = Omit<SpawnOpts, "brief">;

export type ProviderDef = {
  id: ProviderId;
  label: string;
  binaryNames: string[];
  /**
   * Flags only — never the brief. `spawnArgv` appends the brief after
   * these, in the declared form, so the ORDER (brief last, behind `--`
   * for positional providers) is derived once instead of chosen by hand
   * in five places. Must never emit a bare `--` itself: that would turn
   * every later token into an operand.
   */
  buildArgs: (opts: ProviderFlagOpts) => string[];
  /** Declared capabilities — report discovery is DERIVED from this
   * (`deriveReportDiscovery`), never chosen ad hoc in buildArgs / tips. */
  capacity: ProviderCapacity;
  /** DESIGN-BACKLOG.md item 57 ponto 13 — real, current install command
   * per provider (confirmed live against each provider's own docs/npm
   * package, `windows` variant confirmed 2026-09-03): `binary_not_found`
   * surfaces this to the renderer so it can offer a pre-filled (never
   * auto-run) terminal. `null` for `bash` — always resolves via $SHELL/
   * ComSpec, never "not installed". */
  installCommand: InstallCommand | null;
};

export const PROVIDERS: ProviderDef[] = [
  // Bash has no system-prompt injection flag and no provider-specific MCP
  // registration. A manually launched agent inherits AGENT_CANVAS_* and
  // `acbridge` on PATH, but the shell cannot turn that into MCP or show
  // ACBRIDGE_HINT by itself — DESIGN-BACKLOG.md §2.1 point 3. Coverage
  // chosen: human tip via `decideBashCardDiscovery` (pty-registry), not a
  // binary wrapper (forbidden process-name detection) and not --rcfile
  // (would risk clobbering the user's shell rc). Point 4 nested identity
  // stays a known gap — `acbridge claim-card` declined (no cheap handshake).
  {
    id: "bash",
    label: "Bash",
    binaryNames: [],
    buildArgs: () => [],
    installCommand: null,
    capacity: {
      role: "shell",
      systemPrompt: { mechanism: "none" },
      mcp: { mechanism: "none" },
      acbridgeOnPath: true,
      delivery: { briefMechanism: "none", submitStartedPattern: undefined },
    },
  },
  {
    id: "claude",
    label: "Claude",
    binaryNames: ["claude"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "append-system-prompt" },
      mcp: { mechanism: "ephemeral-flag" },
      acbridgeOnPath: true,
      delivery: {
        briefMechanism: "positional",
        submitStartedPattern: /\b(Working|Thinking|Generating|Calculating|Swooping|Finagling|Cogitat(?:ed|ing)?|Moseying|Slithering|Esc to interrupt)\b/i,
      },
    },
    installCommand: {
      posix: "npm install -g @anthropic-ai/claude-code",
      windows: "npm install -g @anthropic-ai/claude-code",
    },
    buildArgs: ({ resumeId, continueLast, imposedSessionId, model, effort, systemPrompt, mcpUrl }) => {
      const args: string[] = [];
      // Restore vs impose are different flags (measured): `--resume`
      // needs a session that already exists; `--session-id` creates one
      // with the UUID Stellar generated. Never both.
      if (resumeId) args.push("--resume", resumeId);
      else if (imposedSessionId) args.push("--session-id", imposedSessionId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      // DESIGN-BACKLOG.md §2.1, 2026-09-09 — real cost to the repo's owner
      // ("a sessão era um opus medium... voltei como high e custou
      // muito"): confirmed via `claude --help` (not assumed, see
      // `SpawnOpts.effort`'s own doc comment) that this flag is real —
      // `--effort <level>` (low/medium/high/xhigh/max). Sent whenever the
      // card has one, same as `model` right above — the two are always
      // read from the same `spawnOpts` object built once in
      // useTerminal.ts, so neither ever reaches here without the other.
      if (effort) args.push("--effort", effort);
      // This is a real Claude CLI flag (`claude --help`). The task prompt
      // and the environment hint are additive; neither should hide the
      // other, so compose them before passing the single appended block.
      args.push("--append-system-prompt", composeSystemPrompt(systemPrompt));
      // Ephemeral registration (DESIGN-BACKLOG.md item 21, ponto 9) — a
      // spawn-scoped `--mcp-config` flag, not a written .mcp.json. Never
      // touches the project's own MCP config, never persists past this
      // one process. `--strict-mcp-config` is deliberately NOT set here —
      // this should ADD to whatever the user's own project already
      // configures, not replace it.
      //
      // `--mcp-config <configs...>` is VARIADIC (`claude --help`): it
      // keeps eating non-option tokens. The brief used to be pushed right
      // here and was read as a second config file (card 471, 2026-09-13,
      // `ENAMETOOLONG`). The brief now arrives via `spawnArgv`, behind
      // `--`, after every flag — nothing positional may follow this.
      if (mcpUrl) {
        args.push(
          "--mcp-config",
          JSON.stringify({ mcpServers: { stellar: { type: "http", url: mcpUrl } } }),
        );
      }
      // Prototipo (2026-09-06) — "unificar detecção de turno" pedido pelo
      // usuário: `isActive` (useTerminal.ts) hoje é só uma aproximação por
      // silêncio de bytes (900ms sem nada = "parou"), documentada como tal
      // no próprio código — faz a barra de atividade sumir mesmo com o
      // agente genuinamente ainda trabalhando (pensando, chamando
      // ferramenta), sem nenhum marcador real de fim de turno. `claude`
      // suporta hooks de verdade — `--settings` (confirmado ao vivo,
      // aceita um JSON string direto, não só path de arquivo) registra um
      // hook `Stop` EFÊMERO, aditivo igual o `--mcp-config` acima (nunca
      // toca `~/.claude/settings.json` nem o `.claude/settings.json` do
      // projeto — sem `--strict-mcp-config` equivalente aqui porque
      // `--settings` já é descrito como "additional settings", soma em
      // vez de substituir). O comando do hook é só `acbridge
      // turn-complete`, sem argumento nenhum — `acbridge` já lê seu
      // próprio `AGENT_CANVAS_CARD_ID` do ambiente (pty-registry.ts's
      // `spawn()` injeta isso em todo processo spawnado), mesmo auto-fill
      // que `report`/`send` já usam. Sinal REAL de fim de turno, não mais
      // heurística — `useTerminal.ts` usa isto pra decidir quando
      // `isActive` vira false, só pra este provider.
      args.push(
        "--settings",
        JSON.stringify({
          hooks: { Stop: [{ hooks: [{ type: "command", command: "acbridge turn-complete" }] }] },
        }),
      );
      return args;
    },
  },
  {
    id: "codex",
    label: "Codex",
    binaryNames: ["codex"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "developer_instructions" },
      mcp: { mechanism: "ephemeral-flag" },
      acbridgeOnPath: true,
      delivery: { briefMechanism: "positional", submitStartedPattern: undefined },
    },
    installCommand: {
      posix: "npm install -g @openai/codex",
      windows: "npm install -g @openai/codex",
    },
    // Codex's resume is a subcommand, must come before any other flag.
    // Codex has no dedicated system-prompt flag, but its real `-c
    // key=value` CLI option (confirmed via `codex --help`) accepts the
    // official `developer_instructions` config key. JSON.stringify produces
    // a valid TOML basic string, including for prompts with quotes/newlines.
    // Variadic audit (`codex --help`, 2026-09-13): only `-i, --image
    // <FILE>...` is variadic, and it is not used here — `-c` is
    // repeatable, one value each. The brief is appended by `spawnArgv`
    // behind `--` (clap honours it, measured) so this stays true even if
    // a variadic flag is added later.
    buildArgs: ({ resumeId, continueLast, model, systemPrompt, mcpUrl }) => {
      const args: string[] = [];
      if (resumeId) args.push("resume", resumeId);
      else if (continueLast) args.push("resume", "--last");
      if (model) args.push("-m", model);
      args.push(
        "-c",
        `developer_instructions=${JSON.stringify(composeSystemPrompt(systemPrompt))}`,
      );
      if (mcpUrl) args.push("-c", `mcp_servers.stellar.url=${mcpUrl}`);
      return args;
    },
  },
  // `cursor` on PATH is usually the IDE launcher; the agent CLI is a
  // separate binary. DESIGN-BACKLOG.md item 57 ponto 13 — confirmed live
  // against cursor.com/docs/cli/installation (2026-08-29) that the
  // installed binary is now named `agent`, not `cursor-agent` — Cursor
  // renamed it at some point after this list was first written ("older
  // articles still use the longer name," per their own docs). Tries the
  // current name first, falls back to the legacy one for an install that
  // predates the rename — same `which()` semantics as every other
  // multi-name lookup already in this file.
  {
    id: "cursor",
    label: "Cursor",
    binaryNames: ["cursor-agent", "agent"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "none" },
      // Global ~/.cursor/mcp.json — headless `agent` DOES read it
      // (measured 2026-09-12). Why no cursor card ever saw the tools
      // anyway, and the fix (`env` interpolation in the entry, because
      // cursor whitelists the MCP child's environment): measured
      // 2026-09-13, documented in mcp-registration.ts. Still insufficient
      // alone for report DISCOVERY (no system-prompt flag) — see
      // deriveReportDiscovery / capacity-contract header.
      mcp: { mechanism: "global-config" },
      acbridgeOnPath: true,
      delivery: {
        briefMechanism: "positional",
        submitStartedPattern: /[\u2800-\u28FF]\s*(?:Running|Reading|Grepping)\b/i,
        // Live 2026-09-14 (card 513): mid-turn send → box `follow-ups` with
        // footer `enter steer · ↑ select/edit · esc cancel`. First Enter
        // parks; second Enter steers into the live turn. get_delivery used
        // to call that park `delivered` (Running neighborhood shifted when
        // the box appeared). Antigravity/claude measured same day: no
        // equivalent box — do not copy this declaration without measuring.
        midTurnQueue: {
          parkedPattern: /\bfollow-ups\b[\s\S]*?\benter\s+steer\b/i,
          steerKey: "\r",
        },
      },
    },
    // Windows confirmado contra cursor.com/docs/cli/installation
    // (2026-09-03) — instalador PowerShell nativo, mesmo endpoint com
    // um query param a mais, sem WSL.
    installCommand: {
      posix: "curl https://cursor.com/install -fsS | bash",
      windows: "irm 'https://cursor.com/install?win32=true' | iex",
    },
    // Sem flag de system-prompt: `prompt` é a entrada do usuário, não um
    // bloco de instruções do sistema. E, ao contrário de claude/codex acima,
    // sem flag efêmera de registro de MCP: a CLI do Cursor só descobre
    // servidor MCP por `.cursor/mcp.json` escrito em disco (do projeto ou
    // global). Escrever no `.cursor/mcp.json` DO PROJETO a cada spawn
    // continua fora de cogitação — é efeito colateral no repositório do
    // usuário. O que mudou (2026-09-01, a pedido): o registro passou a
    // acontecer uma vez só, no config GLOBAL do usuário e apontando pro
    // shim stdio, em `mcp-registration.ts` — fora do `buildArgs`, que é
    // por invocação. Por isso não há nada de MCP nos args aqui.
    // Report discovery is DERIVED as scrollback (capacity.systemPrompt
    // none + acbridgeOnPath) — see decideBashCardDiscovery.
    buildArgs: ({ resumeId, continueLast, imposedSessionId, model }) => {
      const args: string[] = [];
      // Measured: `--resume <uuid>` creates the session when the id does
      // not exist yet. Same flag for restore and impose.
      if (resumeId) args.push("--resume", resumeId);
      else if (imposedSessionId) args.push("--resume", imposedSessionId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      // Positional prompt (`agent [options] [command] [prompt...]`) —
      // measured task 95582065 — is appended by `spawnArgv` behind `--`.
      // Variadic audit (`agent --help`, 2026-09-13): no variadic option;
      // `--add-dir`/`--plugin-dir`/`-H` are repeatable, one value each.
      return args;
    },
  },
  // Pedido ao vivo (2026-08-31) — usuário pediu pra trocar o provider
  // "gemini" por "antigravity": achado ao vivo pesquisando (`gemini`
  // deixou de resolver como CLI própria — a Google aposentou o Gemini
  // CLI e o substituiu pelo Antigravity CLI, um agente de terminal
  // escrito em Go que compartilha motor com o app desktop Antigravity
  // 2.0). Flags confirmadas via busca na documentação real (não
  // adivinhadas): binário `agy`, `--conversation <id>` retoma uma
  // conversa específica por id, `--continue`/`-c` retoma a mais
  // recente, `--model` seleciona o modelo. Sem flag efêmera de
  // registro de MCP por-invocação — confirmado que a única forma é
  // `agy mcp add` (persistente, arquivo `~/.gemini/config/
  // mcp_config.json` ou `.agents/mcp_config.json` por workspace) —
  // Como no cursor logo acima, isso deixou de ser uma não-escolha
  // (2026-09-01, a pedido): `mcp-registration.ts` roda `agy mcp add` uma
  // vez, preguiçosamente, no primeiro spawn de um card antigravity, e
  // aponta pro shim stdio — nunca por spawn, nunca no repositório do
  // usuário. Nada de MCP nos args daqui, que são por invocação.
  {
    id: "antigravity",
    label: "Antigravity",
    binaryNames: ["agy"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "none" },
      mcp: { mechanism: "global-config" },
      acbridgeOnPath: true,
      delivery: {
        briefMechanism: "flag",
        briefFlag: "-i",
        submitStartedPattern: /[\u2800-\u28FF]\s*(Generating|Reviewing Initial Input)\.\.\./i,
      },
    },
    // Windows confirmado contra a documentação real do Antigravity CLI
    // (2026-09-03) — instalador PowerShell nativo, sem WSL (há também uma
    // variante `.cmd` pro prompt puro, mas o PowerShell já cobre o caso
    // padrão sem precisar de um segundo comando por SO).
    installCommand: {
      posix: "curl -fsSL https://antigravity.google/cli/install.sh | bash",
      windows: "irm https://antigravity.google/cli/install.ps1 | iex",
    },
    // Sem flag de system-prompt: `--prompt` é o modo de entrada inicial do
    // usuário, não um canal para acrescentar contexto de ambiente.
    // Report discovery → scrollback (derived). MCP registered via
    // `agy mcp add` in mcp-registration.ts (global-config).
    // No `low|medium|high` guard HERE on purpose (2026-09-10,
    // DESIGN-BACKLOG.md §2.1; range re-measured 2026-09-12) — the real
    // refusal for an out-of-range antigravity effort lives centrally in
    // message-bus.ts's `spawn_agent` handler (`ANTIGRAVITY_EFFORT_VALUES`'s
    // own comment has the full decision),
    // the one place that validates BEFORE any card/process gets created.
    // By the time `buildArgs` runs here, that gate has already passed —
    // duplicating the check would just be a second copy of the same list
    // to keep in sync, not a second layer of real safety (`effort` isn't
    // renderer-writable outside that one path — see providers.ts's
    // `SpawnOpts.effort` doc comment).
    buildArgs: ({ resumeId, continueLast, model, effort }) => {
      const args: string[] = [];
      if (resumeId) args.push("--conversation", resumeId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      if (effort) args.push("--effort", effort);
      // Interactive prompt only: positional is refused (exit 2); `-p` is
      // headless and exits. Measured task 95582065. Form (`-i <brief>`)
      // comes from `delivery.briefFlag`, appended by `spawnArgv`. Go
      // `flag` parser (`agy --help`, 2026-09-13): no variadic option at
      // all, and a flag-carried brief cannot be swallowed anyway.
      return args;
    },
  },
  // Pedido ao vivo (2026-09-04) — worker local (Qwen via llama-server,
  // ver ai memory `qwen-buun-local-server`) precisava de um agente de
  // terminal de verdade (tool-calling real) em vez de só chat cru; em
  // vez de construir um harness próprio, reusa o `opencode` (sst/opencode)
  // já instalado, que já fala com qualquer endpoint OpenAI-compatible via
  // `provider` custom em `~/.config/opencode/opencode.json`. Sem flag
  // efêmera de registro de MCP (confirmado no `--help` real: só
  // `opencode mcp` persistente) — mesma categoria de cursor/antigravity
  // acima, registro fica em `mcp-registration.ts`.
  {
    id: "opencode",
    label: "OpenCode",
    binaryNames: ["opencode"],
    capacity: {
      role: "agent",
      systemPrompt: { mechanism: "none" },
      mcp: { mechanism: "global-config" },
      acbridgeOnPath: true,
      delivery: { briefMechanism: "flag", briefFlag: "--prompt", submitStartedPattern: undefined },
    },
    installCommand: { posix: "npm install -g opencode-ai", windows: "npm install -g opencode-ai" },
    // Sem flag de system-prompt: `--prompt`/mensagens são entrada do
    // usuário; instruções de sistema exigem configuração persistente.
    // Report discovery → scrollback (derived). MCP via global opencode.json.
    buildArgs: ({ resumeId, continueLast, model }) => {
      const args: string[] = [];
      if (resumeId) args.push("--session", resumeId);
      else if (continueLast) args.push("--continue");
      if (model) args.push("--model", model);
      // `--prompt <brief>` appended by `spawnArgv`. yargs (`opencode
      // --help`, 2026-09-13): only `--cors` is an array option; unused.
      return args;
    },
  },
];

/** Providers whose CLI accepts a caller-chosen session id on spawn.
 * Measured 2026-09-13 (task c1064d95): only these two. The other three
 * either refuse an unknown id (`codex`, `opencode`) or ignore it and
 * mint their own (`antigravity`). */
export const IMPOSE_SESSION_ID_PROVIDERS: readonly ProviderId[] = ["claude", "cursor"];

export function canImposeSessionId(providerId: string): boolean {
  return (IMPOSE_SESSION_ID_PROVIDERS as readonly string[]).includes(providerId);
}

/**
 * Whether this spawn should generate a fresh UUID and pass it as
 * `imposedSessionId`. Pure: generation stays at the call site
 * (`randomUUID`) so tests do not mock crypto. A restore (`resumeId`)
 * or `--continue` is never an impose.
 */
export function shouldImposeSessionId(
  providerId: string,
  opts: { resumeId?: string; continueLast?: boolean },
): boolean {
  if (opts.resumeId || opts.continueLast) return false;
  return canImposeSessionId(providerId);
}

export function providerById(id: string): ProviderDef | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

export function providerCapacity(id: string): ProviderCapacity | undefined {
  return providerById(id)?.capacity;
}

/** Achado ao vivo, 2026-09-03 — "no Windows não tem bash": não existe
 * jeito de sugerir `installCommand.posix` numa máquina sem bash/curl. */
export function providerInstallCommand(
  id: string,
  platform: NodeJS.Platform = process.platform,
): string | null {
  const cmd = providerById(id)?.installCommand;
  if (!cmd) return null;
  return platform === "win32" ? cmd.windows : cmd.posix;
}

// Extensões que o Windows tenta, em ordem, quando um nome sem extensão é
// "executado" — mesma lista que o próprio shell do Windows usa (variável
// `PATHEXT`, com um fallback caso ela não exista por algum motivo). Sem
// isso, `which(["claude"])` nunca acharia o shim real que `npm install -g`
// cria lá (`claude.cmd`/`claude.ps1`, nunca um `claude` sem extensão) —
// achado ao vivo, 2026-09-03, junto com o problema do bash acima: a
// detecção de binário em si já não dependia de shell nenhum (sempre foi
// busca de arquivo pura em `process.env.PATH`), só faltava tentar as
// extensões certas por SO.
// Extensões que o Windows tenta, em ordem, quando um nome sem extensão é
// "executado" — mesma lista que o próprio shell do Windows usa (variável
// `PATHEXT`, com um fallback caso ela não exista por algum motivo). Sem
// isso, `which(["claude"])` nunca acharia o shim real que `npm install -g`
// cria lá (`claude.cmd`/`claude.ps1`, nunca um `claude` sem extensão) —
// achado ao vivo, 2026-09-03.
const WINDOWS_EXECUTABLE_EXTENSIONS = (process.env.PATHEXT || ".COM;.EXE;.BAT;.CMD;.PS1")
  .split(";")
  .filter(Boolean);

/** Tudo que `which` precisa saber do mundo, injetável para que o
 * comportamento de OUTRA plataforma seja testável nesta — é a única forma
 * honesta de cobrir o caso macOS sem um Mac, e sem fingir um. */
export type WhichOptions = {
  platform?: NodeJS.Platform;
  /** Diretórios a varrer, em ordem. Default: o PATH efetivo do usuário
   * (`user-env.ts`), NÃO `process.env.PATH` — ver o cabeçalho de lá. */
  pathDirs?: string[];
  /** Default: arquivo de verdade com bit de execução. */
  isExecutable?: (candidate: string) => boolean;
  /** Só para o Windows; default: `PATHEXT` do processo. */
  pathExt?: string[];
};

/**
 * Acha um binário por nome, varrendo diretórios — sem shell nenhuma, o
 * que já era verdade aqui antes e continua sendo.
 *
 * O que mudou (2026-09-08): a lista de diretórios deixou de ser
 * `process.env.PATH` cru. Num `.app` aberto pelo Finder no macOS aquele
 * PATH é o mínimo do launchd e não contém nada que o usuário instalou —
 * ver `user-env.ts` para o porquê e para o que entra no lugar.
 *
 * E o teste de candidato deixou de ser `existsSync`: ele dizia "sim" para
 * um DIRETÓRIO chamado `agent` no PATH (o nome primário da CLI do Cursor,
 * nada improvável) e para um arquivo sem bit de execução.
 */
export function which(
  names: string[],
  platformOrOptions: NodeJS.Platform | WhichOptions = {},
): string | null {
  // Assinatura retrocompatível: os chamadores existentes passam a
  // plataforma direto como segundo argumento.
  const opts: WhichOptions =
    typeof platformOrOptions === "string" ? { platform: platformOrOptions } : platformOrOptions;
  const platform = opts.platform ?? process.platform;
  const isExecutable = opts.isExecutable ?? isExecutableFile;
  const dirs = opts.pathDirs ?? effectivePath().split(delimiter).filter(Boolean);
  const extensions = opts.pathExt ?? WINDOWS_EXECUTABLE_EXTENSIONS;
  const candidateNames =
    platform === "win32"
      ? names.flatMap((name) => [name, ...extensions.map((ext) => name + ext)])
      : names;
  for (const name of candidateNames) {
    for (const dir of dirs) {
      const candidate = join(dir, name);
      if (isExecutable(candidate)) return candidate;
    }
  }
  return null;
}

/** Resolves the binary + args to spawn for a provider. `bash` always
 * resolves via $SHELL no POSIX; no Windows não existe `$SHELL`
 * (variável de ambiente é uma convenção só de shells Unix) nem `/bin/
 * bash` — resolve via `ComSpec` (sempre presente, aponta pro `cmd.exe`
 * real), mesma convenção que o próprio Windows/outras ferramentas
 * (ex. VS Code) usam como shell padrão quando nada mais foi escolhido. */
export function resolveSpawn(
  providerId: string,
  opts: SpawnOpts = {},
): { binary: string; args: string[] } | null {
  const provider = providerById(providerId);
  if (!provider) return null;
  if (provider.id === "bash") {
    if (process.platform === "win32") {
      return { binary: process.env.ComSpec || "C:\\Windows\\System32\\cmd.exe", args: [] };
    }
    // `loginShell()` (user-env.ts) já é a cadeia certa: $SHELL, depois a
    // base de usuário do SO via getpwuid(), e só então um caminho fixo —
    // `/bin/zsh` no macOS, onde é o padrão desde o Catalina, `/bin/sh` no
    // resto, que é o único POSIX obrigatório (`/bin/bash`, o fallback
    // anterior, não existe em toda distro).
    return { binary: loginShell(), args: [] };
  }
  const binary = which(provider.binaryNames);
  if (!binary) return null;
  return { binary, args: spawnArgv(provider, opts) };
}

export type AgentAvailability = {
  id: ProviderId;
  label: string;
  installed: boolean;
  installCommand: string | null;
};

/** Checagem proativa (DESIGN-BACKLOG.md — "aviso antes mesmo de abrir um
 * agente", pedido ao vivo 2026-09-03): roda uma vez, fora do fluxo de
 * spawn de qualquer card, pro Topbar mostrar de cara quais CLIs de agente
 * faltam instalar. `bash` fica de fora — não é uma CLI de agente
 * instalável, é sempre o shell do próprio SO (ver resolveSpawn acima). */
export function checkAgentAvailability(): AgentAvailability[] {
  return PROVIDERS.filter((p) => p.id !== "bash").map((p) => ({
    id: p.id,
    label: p.label,
    installed: which(p.binaryNames) !== null,
    installCommand: providerInstallCommand(p.id),
  }));
}
